export type UserRole = 'admin' | 'farmer' | 'viewer';

export interface User {
  id: string;
  username: string;
  password: string;
  role: UserRole;
  createdAt: string;
  createdBy?: string;
}

export interface OrderItem {
  blockId: string;
  amount: number;
  unit: 'dk' | 'kisten';
}

export interface FarmOrder {
  id: string;
  items: OrderItem[];
  startDate: string;
  deadline: string;
  status: 'open' | 'in_progress' | 'completed' | 'overdue';
  assignedTo?: string[];
  autoAssign: boolean;
  createdBy: string;
  createdAt: string;
  notes?: string;
}

export interface AbsenceRequest {
  id: string;
  username: string;
  startDate: string;
  endDate: string;
  reason?: string;
  status: 'pending' | 'approved' | 'rejected';
  requestedAt: string;
}

export interface MinecraftBlock {
  id: string;
  name: string;
  category: string;
}

export const MINECRAFT_BLOCKS: MinecraftBlock[] = [
  // Baumaterialien
  { id: 'oak_log', name: 'Eichenholz', category: 'Holz' },
  { id: 'spruce_log', name: 'Fichtenholz', category: 'Holz' },
  { id: 'birch_log', name: 'Birkenholz', category: 'Holz' },
  { id: 'jungle_log', name: 'Tropenholz', category: 'Holz' },
  { id: 'acacia_log', name: 'Akazienholz', category: 'Holz' },
  { id: 'dark_oak_log', name: 'Schwarzeichenholz', category: 'Holz' },
  { id: 'mangrove_log', name: 'Mangrovenholz', category: 'Holz' },
  { id: 'cherry_log', name: 'Kirschholz', category: 'Holz' },
  { id: 'pale_oak_log', name: 'Blasseichenholz', category: 'Holz' },
  { id: 'bamboo_block', name: 'Bambusblock', category: 'Holz' },
  { id: 'crimson_stem', name: 'Karmesinstiel', category: 'Holz' },
  { id: 'warped_stem', name: 'Wirrstiel', category: 'Holz' },
  
  // Steine
  { id: 'stone', name: 'Stein', category: 'Steine' },
  { id: 'cobblestone', name: 'Bruchstein', category: 'Steine' },
  { id: 'smooth_stone', name: 'Glatter Stein', category: 'Steine' },
  { id: 'stone_bricks', name: 'Steinziegel', category: 'Steine' },
  { id: 'cracked_stone_bricks', name: 'Rissige Steinziegel', category: 'Steine' },
  { id: 'mossy_stone_bricks', name: 'Bemooste Steinziegel', category: 'Steine' },
  { id: 'chiseled_stone_bricks', name: 'Gemeißelte Steinziegel', category: 'Steine' },
  { id: 'granite', name: 'Granit', category: 'Steine' },
  { id: 'polished_granite', name: 'Polierter Granit', category: 'Steine' },
  { id: 'diorite', name: 'Diorit', category: 'Steine' },
  { id: 'polished_diorite', name: 'Polierter Diorit', category: 'Steine' },
  { id: 'andesite', name: 'Andesit', category: 'Steine' },
  { id: 'polished_andesite', name: 'Polierter Andesit', category: 'Steine' },
  { id: 'deepslate', name: 'Tiefenschiefer', category: 'Steine' },
  { id: 'cobbled_deepslate', name: 'Bruchtiefenschiefer', category: 'Steine' },
  { id: 'polished_deepslate', name: 'Polierter Tiefenschiefer', category: 'Steine' },
  { id: 'deepslate_bricks', name: 'Tiefenschieferziegel', category: 'Steine' },
  { id: 'deepslate_tiles', name: 'Tiefenschieferfliesen', category: 'Steine' },
  { id: 'reinforced_deepslate', name: 'Verstärkter Tiefenschiefer', category: 'Steine' },
  { id: 'tuff', name: 'Tuff', category: 'Steine' },
  { id: 'polished_tuff', name: 'Polierter Tuff', category: 'Steine' },
  { id: 'tuff_bricks', name: 'Tuffziegel', category: 'Steine' },
  { id: 'packed_mud', name: 'Gepresster Schlamm', category: 'Steine' },
  { id: 'mud_bricks', name: 'Schlammziegel', category: 'Steine' },
  
  // Erze
  { id: 'coal_ore', name: 'Kohleerz', category: 'Erze' },
  { id: 'deepslate_coal_ore', name: 'Tiefenschiefer-Kohleerz', category: 'Erze' },
  { id: 'iron_ore', name: 'Eisenerz', category: 'Erze' },
  { id: 'deepslate_iron_ore', name: 'Tiefenschiefer-Eisenerz', category: 'Erze' },
  { id: 'copper_ore', name: 'Kupfererz', category: 'Erze' },
  { id: 'deepslate_copper_ore', name: 'Tiefenschiefer-Kupfererz', category: 'Erze' },
  { id: 'gold_ore', name: 'Golderz', category: 'Erze' },
  { id: 'deepslate_gold_ore', name: 'Tiefenschiefer-Golderz', category: 'Erze' },
  { id: 'redstone_ore', name: 'Redstone-Erz', category: 'Erze' },
  { id: 'deepslate_redstone_ore', name: 'Tiefenschiefer-Redstone-Erz', category: 'Erze' },
  { id: 'emerald_ore', name: 'Smaragderz', category: 'Erze' },
  { id: 'deepslate_emerald_ore', name: 'Tiefenschiefer-Smaragderz', category: 'Erze' },
  { id: 'lapis_ore', name: 'Lapislazulierz', category: 'Erze' },
  { id: 'deepslate_lapis_ore', name: 'Tiefenschiefer-Lapislazulierz', category: 'Erze' },
  { id: 'diamond_ore', name: 'Diamanterz', category: 'Erze' },
  { id: 'deepslate_diamond_ore', name: 'Tiefenschiefer-Diamanterz', category: 'Erze' },
  { id: 'nether_gold_ore', name: 'Nether-Golderz', category: 'Erze' },
  { id: 'ancient_debris', name: 'Antiker Schrott', category: 'Erze' },
  { id: 'nether_quartz_ore', name: 'Nether-Quarzerz', category: 'Erze' },
  
  // Mineralien
  { id: 'coal_block', name: 'Kohleblock', category: 'Mineralien' },
  { id: 'iron_block', name: 'Eisenblock', category: 'Mineralien' },
  { id: 'copper_block', name: 'Kupferblock', category: 'Mineralien' },
  { id: 'exposed_copper', name: 'Angelaufener Kupferblock', category: 'Mineralien' },
  { id: 'weathered_copper', name: 'Verwitterter Kupferblock', category: 'Mineralien' },
  { id: 'oxidized_copper', name: 'Oxidierter Kupferblock', category: 'Mineralien' },
  { id: 'cut_copper', name: 'Geschnittener Kupferblock', category: 'Mineralien' },
  { id: 'gold_block', name: 'Goldblock', category: 'Mineralien' },
  { id: 'redstone_block', name: 'Redstone-Block', category: 'Mineralien' },
  { id: 'emerald_block', name: 'Smaragdblock', category: 'Mineralien' },
  { id: 'lapis_block', name: 'Lapislazuliblock', category: 'Mineralien' },
  { id: 'diamond_block', name: 'Diamantblock', category: 'Mineralien' },
  { id: 'netherite_block', name: 'Netheritblock', category: 'Mineralien' },
  { id: 'quartz_block', name: 'Quarzblock', category: 'Mineralien' },
  { id: 'chiseled_quartz_block', name: 'Gemeißelter Quarzblock', category: 'Mineralien' },
  { id: 'quartz_pillar', name: 'Quarzsäule', category: 'Mineralien' },
  { id: 'smooth_quartz', name: 'Glatte Quarzblock', category: 'Mineralien' },
  { id: 'quartz_bricks', name: 'Quarzziegel', category: 'Mineralien' },
  { id: 'amethyst_block', name: 'Amethystblock', category: 'Mineralien' },
  { id: 'budding_amethyst', name: 'Amethystknospenblock', category: 'Mineralien' },
  { id: 'small_amethyst_bud', name: 'Kleine Amethystknospe', category: 'Mineralien' },
  { id: 'medium_amethyst_bud', name: 'Mittlere Amethystknospe', category: 'Mineralien' },
  { id: 'large_amethyst_bud', name: 'Große Amethystknospe', category: 'Mineralien' },
  { id: 'amethyst_cluster', name: 'Amethysthaufen', category: 'Mineralien' },
  
  // Nether
  { id: 'netherrack', name: 'Netherrack', category: 'Nether' },
  { id: 'nether_bricks', name: 'Netherziegel', category: 'Nether' },
  { id: 'cracked_nether_bricks', name: 'Rissige Netherziegel', category: 'Nether' },
  { id: 'chiseled_nether_bricks', name: 'Gemeißelte Netherziegel', category: 'Nether' },
  { id: 'red_nether_bricks', name: 'Rote Netherziegel', category: 'Nether' },
  { id: 'soul_sand', name: 'Seelensand', category: 'Nether' },
  { id: 'soul_soil', name: 'Seelenerde', category: 'Nether' },
  { id: 'basalt', name: 'Basalt', category: 'Nether' },
  { id: 'smooth_basalt', name: 'Glatter Basalt', category: 'Nether' },
  { id: 'polished_basalt', name: 'Polierter Basalt', category: 'Nether' },
  { id: 'blackstone', name: 'Schwarzstein', category: 'Nether' },
  { id: 'gilded_blackstone', name: 'Vergoldeter Schwarzstein', category: 'Nether' },
  { id: 'polished_blackstone', name: 'Polierter Schwarzstein', category: 'Nether' },
  { id: 'polished_blackstone_bricks', name: 'Polierte Schwarzsteinziegel', category: 'Nether' },
  { id: 'cracked_polished_blackstone_bricks', name: 'Rissige polierte Schwarzsteinziegel', category: 'Nether' },
  { id: 'chiseled_polished_blackstone', name: 'Gemeißelter polierter Schwarzstein', category: 'Nether' },
  { id: 'magma_block', name: 'Magmablock', category: 'Nether' },
  { id: 'glowstone', name: 'Glowstone', category: 'Nether' },
  { id: 'shroomlight', name: 'Pilzlicht', category: 'Nether' },
  { id: 'warped_nylium', name: 'Wirr-Nezel', category: 'Nether' },
  { id: 'crimson_nylium', name: 'Karmesin-Nezel', category: 'Nether' },
  { id: 'warped_wart_block', name: 'Wirrwarzenblock', category: 'Nether' },
  { id: 'nether_wart_block', name: 'Netherwarzenblock', category: 'Nether' },
  { id: 'soul_fire_lantern', name: 'Seelenfeuerlaterne', category: 'Nether' },
  { id: 'soul_torch', name: 'Seelenfackel', category: 'Nether' },
  
  // End
  { id: 'end_stone', name: 'Endstein', category: 'End' },
  { id: 'end_stone_bricks', name: 'Endsteinziegel', category: 'End' },
  { id: 'purpur_block', name: 'Purpurblock', category: 'End' },
  { id: 'purpur_pillar', name: 'Purpursäule', category: 'End' },
  { id: 'end_rod', name: 'Endstab', category: 'End' },
  { id: 'dragon_egg', name: 'Drachenei', category: 'End' },
  { id: 'dragon_head', name: 'Drachenkopf', category: 'End' },
  
  // Natur
  { id: 'grass_block', name: 'Grasblock', category: 'Natur' },
  { id: 'dirt', name: 'Erde', category: 'Natur' },
  { id: 'coarse_dirt', name: 'Grobe Erde', category: 'Natur' },
  { id: 'podzol', name: 'Podsol', category: 'Natur' },
  { id: 'rooted_dirt', name: 'Bewurzelte Erde', category: 'Natur' },
  { id: 'mud', name: 'Schlamm', category: 'Natur' },
  { id: 'clay', name: 'Ton', category: 'Natur' },
  { id: 'gravel', name: 'Kies', category: 'Natur' },
  { id: 'sand', name: 'Sand', category: 'Natur' },
  { id: 'red_sand', name: 'Roter Sand', category: 'Natur' },
  { id: 'sandstone', name: 'Sandstein', category: 'Natur' },
  { id: 'red_sandstone', name: 'Roter Sandstein', category: 'Natur' },
  { id: 'cut_sandstone', name: 'Geschnittener Sandstein', category: 'Natur' },
  { id: 'cut_red_sandstone', name: 'Geschnittener roter Sandstein', category: 'Natur' },
  { id: 'chiseled_sandstone', name: 'Gemeißelter Sandstein', category: 'Natur' },
  { id: 'chiseled_red_sandstone', name: 'Gemeißelter roter Sandstein', category: 'Natur' },
  { id: 'smooth_sandstone', name: 'Glatter Sandstein', category: 'Natur' },
  { id: 'smooth_red_sandstone', name: 'Glatter roter Sandstein', category: 'Natur' },
  { id: 'moss_block', name: 'Moosblock', category: 'Natur' },
  { id: 'moss_carpet', name: 'Moosteppich', category: 'Natur' },
  { id: 'pale_moss_block', name: 'Blasses Moosblock', category: 'Natur' },
  { id: 'pale_moss_carpet', name: 'Blasser Moosteppich', category: 'Natur' },
  { id: 'dripstone_block', name: 'Tropfsteinblock', category: 'Natur' },
  { id: 'pointed_dripstone', name: 'Spitzer Tropfstein', category: 'Natur' },
  { id: 'ice', name: 'Eis', category: 'Natur' },
  { id: 'packed_ice', name: 'Packeis', category: 'Natur' },
  { id: 'blue_ice', name: 'Blaueis', category: 'Natur' },
  { id: 'snow_block', name: 'Schneeblock', category: 'Natur' },
  { id: 'snow', name: 'Schnee', category: 'Natur' },
  { id: 'powder_snow', name: 'Pulverschnee', category: 'Natur' },
  { id: 'obsidian', name: 'Obsidian', category: 'Natur' },
  { id: 'crying_obsidian', name: 'Weinender Obsidian', category: 'Natur' },
  { id: 'bedrock', name: 'Grundgestein', category: 'Natur' },
  { id: 'soul_campfire', name: 'Seelenlagerfeuer', category: 'Natur' },
  { id: 'campfire', name: 'Lagerfeuer', category: 'Natur' },
  
  // Pflanzen
  { id: 'oak_leaves', name: 'Eichenlaub', category: 'Pflanzen' },
  { id: 'spruce_leaves', name: 'Fichtenlaub', category: 'Pflanzen' },
  { id: 'birch_leaves', name: 'Birkenlaub', category: 'Pflanzen' },
  { id: 'jungle_leaves', name: 'Tropenlaub', category: 'Pflanzen' },
  { id: 'acacia_leaves', name: 'Akazienlaub', category: 'Pflanzen' },
  { id: 'dark_oak_leaves', name: 'Schwarzeichenlaub', category: 'Pflanzen' },
  { id: 'mangrove_leaves', name: 'Mangrovenlaub', category: 'Pflanzen' },
  { id: 'cherry_leaves', name: 'Kirschlaub', category: 'Pflanzen' },
  { id: 'pale_oak_leaves', name: 'Blasseichenlaub', category: 'Pflanzen' },
  { id: 'azalea_leaves', name: 'Azaleenlaub', category: 'Pflanzen' },
  { id: 'flowering_azalea_leaves', name: 'Blühendes Azaleenlaub', category: 'Pflanzen' },
  { id: 'oak_sapling', name: 'Eichensetzling', category: 'Pflanzen' },
  { id: 'spruce_sapling', name: 'Fichtensetzling', category: 'Pflanzen' },
  { id: 'birch_sapling', name: 'Birkensetzling', category: 'Pflanzen' },
  { id: 'jungle_sapling', name: 'Tropensetzling', category: 'Pflanzen' },
  { id: 'acacia_sapling', name: 'Akaziensetzling', category: 'Pflanzen' },
  { id: 'dark_oak_sapling', name: 'Schwarzeichensetzling', category: 'Pflanzen' },
  { id: 'mangrove_propagule', name: 'Mangrovenkeimling', category: 'Pflanzen' },
  { id: 'cherry_sapling', name: 'Kirschsetzling', category: 'Pflanzen' },
  { id: 'pale_oak_sapling', name: 'Blasseichensetzling', category: 'Pflanzen' },
  { id: 'azalea', name: 'Azalee', category: 'Pflanzen' },
  { id: 'flowering_azalea', name: 'Blühende Azalee', category: 'Pflanzen' },
  { id: 'grass', name: 'Gras', category: 'Pflanzen' },
  { id: 'tall_grass', name: 'Hohes Gras', category: 'Pflanzen' },
  { id: 'fern', name: 'Farn', category: 'Pflanzen' },
  { id: 'large_fern', name: 'Großer Farn', category: 'Pflanzen' },
  { id: 'dead_bush', name: 'Toter Busch', category: 'Pflanzen' },
  { id: 'seagrass', name: 'Seegras', category: 'Pflanzen' },
  { id: 'tall_seagrass', name: 'Hohes Seegras', category: 'Pflanzen' },
  { id: 'sea_pickle', name: 'Seegurke', category: 'Pflanzen' },
  { id: 'cactus', name: 'Kaktus', category: 'Pflanzen' },
  { id: 'sugar_cane', name: 'Zuckerrohr', category: 'Pflanzen' },
  { id: 'bamboo', name: 'Bambus', category: 'Pflanzen' },
  { id: 'vine', name: 'Ranken', category: 'Pflanzen' },
  { id: 'weeping_vines', name: 'Trauerranken', category: 'Pflanzen' },
  { id: 'twisting_vines', name: 'Zwirbelranken', category: 'Pflanzen' },
  { id: 'cave_vines', name: 'Höhlenranken', category: 'Pflanzen' },
  { id: 'glow_lichen', name: 'Leuchtflechte', category: 'Pflanzen' },
  { id: 'sculk_vein', name: 'Sculk-Ader', category: 'Pflanzen' },
  { id: 'sculk', name: 'Sculk', category: 'Pflanzen' },
  { id: 'sculk_catalyst', name: 'Sculk-Katalysator', category: 'Pflanzen' },
  { id: 'sculk_shrieker', name: 'Sculk-Kreischer', category: 'Pflanzen' },
  { id: 'sculk_sensor', name: 'Sculk-Sensor', category: 'Pflanzen' },
  { id: 'lily_pad', name: 'Seerosenblatt', category: 'Pflanzen' },
  { id: 'spore_blossom', name: 'Sporenblüte', category: 'Pflanzen' },
  { id: 'big_dripleaf', name: 'Großes Tropfblatt', category: 'Pflanzen' },
  { id: 'small_dripleaf', name: 'Kleines Tropfblatt', category: 'Pflanzen' },
  { id: 'hanging_roots', name: 'Hängende Wurzeln', category: 'Pflanzen' },
  { id: 'nether_sprouts', name: 'Nethersprossen', category: 'Pflanzen' },
  { id: 'crimson_roots', name: 'Karmesinwurzeln', category: 'Pflanzen' },
  { id: 'warped_roots', name: 'Wirrwurzeln', category: 'Pflanzen' },
  { id: 'crimson_fungus', name: 'Karmesinpilz', category: 'Pflanzen' },
  { id: 'warped_fungus', name: 'Wirrpilz', category: 'Pflanzen' },
  { id: 'brown_mushroom', name: 'Brauner Pilz', category: 'Pflanzen' },
  { id: 'red_mushroom', name: 'Roter Pilz', category: 'Pflanzen' },
  { id: 'mushroom_stem', name: 'Pilzstiel', category: 'Pflanzen' },
  { id: 'brown_mushroom_block', name: 'Brauner Pilzblock', category: 'Pflanzen' },
  { id: 'red_mushroom_block', name: 'Roter Pilzblock', category: 'Pflanzen' },
  { id: 'chorus_plant', name: 'Choruspflanze', category: 'Pflanzen' },
  { id: 'chorus_flower', name: 'Chorusblüte', category: 'Pflanzen' },
  { id: 'chorus_fruit', name: 'Chorusfrucht', category: 'Pflanzen' },
  { id: 'popped_chorus_fruit', name: 'Geplatzte Chorusfrucht', category: 'Pflanzen' },
  
  // Blumen
  { id: 'dandelion', name: 'Löwenzahn', category: 'Blumen' },
  { id: 'poppy', name: 'Mohn', category: 'Blumen' },
  { id: 'blue_orchid', name: 'Blaue Orchidee', category: 'Blumen' },
  { id: 'allium', name: 'Allium', category: 'Blumen' },
  { id: 'azure_bluet', name: 'Porzellansternchen', category: 'Blumen' },
  { id: 'red_tulip', name: 'Rote Tulpe', category: 'Blumen' },
  { id: 'orange_tulip', name: 'Orange Tulpe', category: 'Blumen' },
  { id: 'white_tulip', name: 'Weiße Tulpe', category: 'Blumen' },
  { id: 'pink_tulip', name: 'Rosa Tulpe', category: 'Blumen' },
  { id: 'oxeye_daisy', name: 'Margerite', category: 'Blumen' },
  { id: 'cornflower', name: 'Kornblume', category: 'Blumen' },
  { id: 'lily_of_the_valley', name: 'Maiglöckchen', category: 'Blumen' },
  { id: 'sunflower', name: 'Sonnenblume', category: 'Blumen' },
  { id: 'lilac', name: 'Flieder', category: 'Blumen' },
  { id: 'rose_bush', name: 'Rosenstrauch', category: 'Blumen' },
  { id: 'peony', name: 'Pfingstrose', category: 'Blumen' },
  { id: 'pink_petals', name: 'Rosa Blütenblätter', category: 'Blumen' },
  { id: 'wildflowers', name: 'Wildblumen', category: 'Blumen' },
  { id: 'leaf_litter', name: 'Laubstreu', category: 'Blumen' },
  { id: 'firefly_bush', name: 'Glühwürmchenbusch', category: 'Blumen' },
  { id: 'cactus_flower', name: 'Kaktusblüte', category: 'Blumen' },
  { id: 'chorus_flower', name: 'Chorusblüte', category: 'Blumen' },
  { id: 'wither_rose', name: 'Witherrose', category: 'Blumen' },
  { id: 'torchflower', name: 'Fackellilie', category: 'Blumen' },
  { id: 'pitcher_plant', name: 'Kannenpflanze', category: 'Blumen' },
  { id: 'open_eyeblossom', name: 'Offene Augenblüte', category: 'Blumen' },
  { id: 'closed_eyeblossom', name: 'Geschlossene Augenblüte', category: 'Blumen' },
  
  // Kulturen
  { id: 'wheat', name: 'Weizen', category: 'Kulturen' },
  { id: 'wheat_seeds', name: 'Weizensamen', category: 'Kulturen' },
  { id: 'carrot', name: 'Karotte', category: 'Kulturen' },
  { id: 'potato', name: 'Kartoffel', category: 'Kulturen' },
  { id: 'poisonous_potato', name: 'Giftige Kartoffel', category: 'Kulturen' },
  { id: 'beetroot', name: 'Rote Bete', category: 'Kulturen' },
  { id: 'beetroot_seeds', name: 'Rote-Bete-Samen', category: 'Kulturen' },
  { id: 'melon', name: 'Melone', category: 'Kulturen' },
  { id: 'melon_slice', name: 'Melonenscheibe', category: 'Kulturen' },
  { id: 'glistering_melon_slice', name: 'Glitzernde Melonenscheibe', category: 'Kulturen' },
  { id: 'pumpkin', name: 'Kürbis', category: 'Kulturen' },
  { id: 'carved_pumpkin', name: 'Geschnitzter Kürbis', category: 'Kulturen' },
  { id: 'jack_o_lantern', name: 'Kürbislaterne', category: 'Kulturen' },
  { id: 'sweet_berries', name: 'Süßbeeren', category: 'Kulturen' },
  { id: 'glow_berries', name: 'Leuchtbeeren', category: 'Kulturen' },
  { id: 'cocoa_beans', name: 'Kakaobohnen', category: 'Kulturen' },
  { id: 'nether_wart', name: 'Netherwarze', category: 'Kulturen' },
  { id: 'kelp', name: 'Kelp', category: 'Kulturen' },
  { id: 'dried_kelp', name: 'Getrockneter Kelp', category: 'Kulturen' },
  { id: 'dried_kelp_block', name: 'Getrockneter-Kelp-Block', category: 'Kulturen' },
  
  // Farbstoffe
  { id: 'ink_sac', name: 'Tintenbeutel', category: 'Farbstoffe' },
  { id: 'glow_ink_sac', name: 'Leucht-Tintenbeutel', category: 'Farbstoffe' },
  { id: 'cocoa_beans', name: 'Kakaobohnen', category: 'Farbstoffe' },
  { id: 'lapis_lazuli', name: 'Lapislazuli', category: 'Farbstoffe' },
  { id: 'bone_meal', name: 'Knochenmehl', category: 'Farbstoffe' },
  { id: 'white_dye', name: 'Weißer Farbstoff', category: 'Farbstoffe' },
  { id: 'orange_dye', name: 'Oranger Farbstoff', category: 'Farbstoffe' },
  { id: 'magenta_dye', name: 'Magenta Farbstoff', category: 'Farbstoffe' },
  { id: 'light_blue_dye', name: 'Hellblauer Farbstoff', category: 'Farbstoffe' },
  { id: 'yellow_dye', name: 'Gelber Farbstoff', category: 'Farbstoffe' },
  { id: 'lime_dye', name: 'Hellgrüner Farbstoff', category: 'Farbstoffe' },
  { id: 'pink_dye', name: 'Rosa Farbstoff', category: 'Farbstoffe' },
  { id: 'gray_dye', name: 'Grauer Farbstoff', category: 'Farbstoffe' },
  { id: 'light_gray_dye', name: 'Hellgrauer Farbstoff', category: 'Farbstoffe' },
  { id: 'cyan_dye', name: 'Türkiser Farbstoff', category: 'Farbstoffe' },
  { id: 'purple_dye', name: 'Violetter Farbstoff', category: 'Farbstoffe' },
  { id: 'blue_dye', name: 'Blauer Farbstoff', category: 'Farbstoffe' },
  { id: 'brown_dye', name: 'Brauner Farbstoff', category: 'Farbstoffe' },
  { id: 'green_dye', name: 'Grüner Farbstoff', category: 'Farbstoffe' },
  { id: 'red_dye', name: 'Roter Farbstoff', category: 'Farbstoffe' },
  { id: 'black_dye', name: 'Schwarzer Farbstoff', category: 'Farbstoffe' },
  
  // Redstone
  { id: 'redstone', name: 'Redstone-Staub', category: 'Redstone' },
  { id: 'redstone_torch', name: 'Redstone-Fackel', category: 'Redstone' },
  { id: 'redstone_repeater', name: 'Redstone-Verstärker', category: 'Redstone' },
  { id: 'redstone_comparator', name: 'Redstone-Komparator', category: 'Redstone' },
  { id: 'piston', name: 'Kolben', category: 'Redstone' },
  { id: 'sticky_piston', name: 'Klebriger Kolben', category: 'Redstone' },
  { id: 'slime_block', name: 'Schleimblock', category: 'Redstone' },
  { id: 'honey_block', name: 'Honigblock', category: 'Redstone' },
  { id: 'observer', name: 'Beobachter', category: 'Redstone' },
  { id: 'hopper', name: 'Trichter', category: 'Redstone' },
  { id: 'dropper', name: 'Spender', category: 'Redstone' },
  { id: 'dispenser', name: 'Werfer', category: 'Redstone' },
  { id: 'note_block', name: 'Notenblock', category: 'Redstone' },
  { id: 'tnt', name: 'TNT', category: 'Redstone' },
  { id: 'daylight_detector', name: 'Tageslichtsensor', category: 'Redstone' },
  { id: 'tripwire_hook', name: 'Haken', category: 'Redstone' },
  { id: 'string', name: 'Faden', category: 'Redstone' },
  { id: 'lectern', name: 'Lesepult', category: 'Redstone' },
  { id: 'target', name: 'Zielblock', category: 'Redstone' },
  { id: 'lightning_rod', name: 'Blitzableiter', category: 'Redstone' },
  { id: 'sculk_sensor', name: 'Sculk-Sensor', category: 'Redstone' },
  { id: 'calibrated_sculk_sensor', name: 'Kalibrierter Sculk-Sensor', category: 'Redstone' },
  { id: 'chiseled_bookshelf', name: 'Gemeißeltes Bücherregal', category: 'Redstone' },
  { id: 'crafter', name: 'Werkbank', category: 'Redstone' },
  
  // Dekoration
  { id: 'cobweb', name: 'Spinnennetz', category: 'Dekoration' },
  { id: 'rail', name: 'Schiene', category: 'Dekoration' },
  { id: 'powered_rail', name: 'Antriebsschiene', category: 'Dekoration' },
  { id: 'detector_rail', name: 'Sensorschiene', category: 'Dekoration' },
  { id: 'activator_rail', name: 'Aktivierungsschiene', category: 'Dekoration' },
  { id: 'torch', name: 'Fackel', category: 'Dekoration' },
  { id: 'soul_torch', name: 'Seelenfackel', category: 'Dekoration' },
  { id: 'redstone_torch', name: 'Redstone-Fackel', category: 'Dekoration' },
  { id: 'lantern', name: 'Laterne', category: 'Dekoration' },
  { id: 'soul_lantern', name: 'Seelenlaterne', category: 'Dekoration' },
  { id: 'end_rod', name: 'Endstab', category: 'Dekoration' },
  { id: 'sea_lantern', name: 'Seelaterne', category: 'Dekoration' },
  { id: 'redstone_lamp', name: 'Redstone-Lampe', category: 'Dekoration' },
  { id: 'glowstone', name: 'Glowstone', category: 'Dekoration' },
  { id: 'shroomlight', name: 'Pilzlicht', category: 'Dekoration' },
  { id: 'ochre_froglight', name: 'Ocker-Froschlicht', category: 'Dekoration' },
  { id: 'verdant_froglight', name: 'Grünes Froschlicht', category: 'Dekoration' },
  { id: 'pearlescent_froglight', name: 'Perlmutt-Froschlicht', category: 'Dekoration' },
  { id: 'candle', name: 'Kerze', category: 'Dekoration' },
  { id: 'white_candle', name: 'Weiße Kerze', category: 'Dekoration' },
  { id: 'orange_candle', name: 'Orange Kerze', category: 'Dekoration' },
  { id: 'magenta_candle', name: 'Magenta Kerze', category: 'Dekoration' },
  { id: 'light_blue_candle', name: 'Hellblaue Kerze', category: 'Dekoration' },
  { id: 'yellow_candle', name: 'Gelbe Kerze', category: 'Dekoration' },
  { id: 'lime_candle', name: 'Hellgrüne Kerze', category: 'Dekoration' },
  { id: 'pink_candle', name: 'Rosa Kerze', category: 'Dekoration' },
  { id: 'gray_candle', name: 'Graue Kerze', category: 'Dekoration' },
  { id: 'light_gray_candle', name: 'Hellgraue Kerze', category: 'Dekoration' },
  { id: 'cyan_candle', name: 'Türkise Kerze', category: 'Dekoration' },
  { id: 'purple_candle', name: 'Violette Kerze', category: 'Dekoration' },
  { id: 'blue_candle', name: 'Blaue Kerze', category: 'Dekoration' },
  { id: 'brown_candle', name: 'Braune Kerze', category: 'Dekoration' },
  { id: 'green_candle', name: 'Grüne Kerze', category: 'Dekoration' },
  { id: 'red_candle', name: 'Rote Kerze', category: 'Dekoration' },
  { id: 'black_candle', name: 'Schwarze Kerze', category: 'Dekoration' },
  { id: 'ladder', name: 'Leiter', category: 'Dekoration' },
  { id: 'scaffolding', name: 'Gerüst', category: 'Dekoration' },
  { id: 'armor_stand', name: 'Rüstungsständer', category: 'Dekoration' },
  { id: 'item_frame', name: 'Rahmen', category: 'Dekoration' },
  { id: 'glow_item_frame', name: 'Leuchtrahmen', category: 'Dekoration' },
  { id: 'painting', name: 'Gemälde', category: 'Dekoration' },
  { id: 'flower_pot', name: 'Blumentopf', category: 'Dekoration' },
  { id: 'decorated_pot', name: 'Verzierter Krug', category: 'Dekoration' },
  { id: 'skull', name: 'Kopf', category: 'Dekoration' },
  { id: 'skeleton_skull', name: 'Skelettschädel', category: 'Dekoration' },
  { id: 'wither_skeleton_skull', name: 'Wither-Skelettschädel', category: 'Dekoration' },
  { id: 'zombie_head', name: 'Zombiekopf', category: 'Dekoration' },
  { id: 'player_head', name: 'Spielerkopf', category: 'Dekoration' },
  { id: 'creeper_head', name: 'Creeper-Kopf', category: 'Dekoration' },
  { id: 'dragon_head', name: 'Drachenkopf', category: 'Dekoration' },
  { id: 'piglin_head', name: 'Piglin-Kopf', category: 'Dekoration' },
  { id: 'end_crystal', name: 'Endkristall', category: 'Dekoration' },
  { id: 'respawn_anchor', name: 'Seelenanker', category: 'Dekoration' },
  { id: 'bed', name: 'Bett', category: 'Dekoration' },
  { id: 'white_bed', name: 'Weißes Bett', category: 'Dekoration' },
  { id: 'orange_bed', name: 'Oranges Bett', category: 'Dekoration' },
  { id: 'magenta_bed', name: 'Magenta Bett', category: 'Dekoration' },
  { id: 'light_blue_bed', name: 'Hellblaues Bett', category: 'Dekoration' },
  { id: 'yellow_bed', name: 'Gelbes Bett', category: 'Dekoration' },
  { id: 'lime_bed', name: 'Hellgrünes Bett', category: 'Dekoration' },
  { id: 'pink_bed', name: 'Rosa Bett', category: 'Dekoration' },
  { id: 'gray_bed', name: 'Graues Bett', category: 'Dekoration' },
  { id: 'light_gray_bed', name: 'Hellgraues Bett', category: 'Dekoration' },
  { id: 'cyan_bed', name: 'Türkises Bett', category: 'Dekoration' },
  { id: 'purple_bed', name: 'Violettes Bett', category: 'Dekoration' },
  { id: 'blue_bed', name: 'Blaues Bett', category: 'Dekoration' },
  { id: 'brown_bed', name: 'Braunes Bett', category: 'Dekoration' },
  { id: 'green_bed', name: 'Grünes Bett', category: 'Dekoration' },
  { id: 'red_bed', name: 'Rotes Bett', category: 'Dekoration' },
  { id: 'black_bed', name: 'Schwarzes Bett', category: 'Dekoration' },
  { id: 'banner', name: 'Banner', category: 'Dekoration' },
  { id: 'white_banner', name: 'Weißes Banner', category: 'Dekoration' },
  { id: 'orange_banner', name: 'Oranges Banner', category: 'Dekoration' },
  { id: 'magenta_banner', name: 'Magenta Banner', category: 'Dekoration' },
  { id: 'light_blue_banner', name: 'Hellblaues Banner', category: 'Dekoration' },
  { id: 'yellow_banner', name: 'Gelbes Banner', category: 'Dekoration' },
  { id: 'lime_banner', name: 'Hellgrünes Banner', category: 'Dekoration' },
  { id: 'pink_banner', name: 'Rosa Banner', category: 'Dekoration' },
  { id: 'gray_banner', name: 'Graues Banner', category: 'Dekoration' },
  { id: 'light_gray_banner', name: 'Hellgraues Banner', category: 'Dekoration' },
  { id: 'cyan_banner', name: 'Türkises Banner', category: 'Dekoration' },
  { id: 'purple_banner', name: 'Violettes Banner', category: 'Dekoration' },
  { id: 'blue_banner', name: 'Blaues Banner', category: 'Dekoration' },
  { id: 'brown_banner', name: 'Braunes Banner', category: 'Dekoration' },
  { id: 'green_banner', name: 'Grünes Banner', category: 'Dekoration' },
  { id: 'red_banner', name: 'Rotes Banner', category: 'Dekoration' },
  { id: 'black_banner', name: 'Schwarzes Banner', category: 'Dekoration' },
  { id: 'shield', name: 'Schild', category: 'Dekoration' },
  
  // Glas
  { id: 'glass', name: 'Glas', category: 'Glas' },
  { id: 'tinted_glass', name: 'Getöntes Glas', category: 'Glas' },
  { id: 'white_stained_glass', name: 'Weißes Glas', category: 'Glas' },
  { id: 'orange_stained_glass', name: 'Oranges Glas', category: 'Glas' },
  { id: 'magenta_stained_glass', name: 'Magenta Glas', category: 'Glas' },
  { id: 'light_blue_stained_glass', name: 'Hellblaues Glas', category: 'Glas' },
  { id: 'yellow_stained_glass', name: 'Gelbes Glas', category: 'Glas' },
  { id: 'lime_stained_glass', name: 'Hellgrünes Glas', category: 'Glas' },
  { id: 'pink_stained_glass', name: 'Rosa Glas', category: 'Glas' },
  { id: 'gray_stained_glass', name: 'Graues Glas', category: 'Glas' },
  { id: 'light_gray_stained_glass', name: 'Hellgraues Glas', category: 'Glas' },
  { id: 'cyan_stained_glass', name: 'Türkises Glas', category: 'Glas' },
  { id: 'purple_stained_glass', name: 'Violettes Glas', category: 'Glas' },
  { id: 'blue_stained_glass', name: 'Blaues Glas', category: 'Glas' },
  { id: 'brown_stained_glass', name: 'Braunes Glas', category: 'Glas' },
  { id: 'green_stained_glass', name: 'Grünes Glas', category: 'Glas' },
  { id: 'red_stained_glass', name: 'Rotes Glas', category: 'Glas' },
  { id: 'black_stained_glass', name: 'Schwarzes Glas', category: 'Glas' },
  { id: 'glass_pane', name: 'Glasscheibe', category: 'Glas' },
  { id: 'white_stained_glass_pane', name: 'Weiße Glasscheibe', category: 'Glas' },
  { id: 'orange_stained_glass_pane', name: 'Orange Glasscheibe', category: 'Glas' },
  { id: 'magenta_stained_glass_pane', name: 'Magenta Glasscheibe', category: 'Glas' },
  { id: 'light_blue_stained_glass_pane', name: 'Hellblaue Glasscheibe', category: 'Glas' },
  { id: 'yellow_stained_glass_pane', name: 'Gelbe Glasscheibe', category: 'Glas' },
  { id: 'lime_stained_glass_pane', name: 'Hellgrüne Glasscheibe', category: 'Glas' },
  { id: 'pink_stained_glass_pane', name: 'Rosa Glasscheibe', category: 'Glas' },
  { id: 'gray_stained_glass_pane', name: 'Graue Glasscheibe', category: 'Glas' },
  { id: 'light_gray_stained_glass_pane', name: 'Hellgraue Glasscheibe', category: 'Glas' },
  { id: 'cyan_stained_glass_pane', name: 'Türkise Glasscheibe', category: 'Glas' },
  { id: 'purple_stained_glass_pane', name: 'Violette Glasscheibe', category: 'Glas' },
  { id: 'blue_stained_glass_pane', name: 'Blaue Glasscheibe', category: 'Glas' },
  { id: 'brown_stained_glass_pane', name: 'Braune Glasscheibe', category: 'Glas' },
  { id: 'green_stained_glass_pane', name: 'Grüne Glasscheibe', category: 'Glas' },
  { id: 'red_stained_glass_pane', name: 'Rote Glasscheibe', category: 'Glas' },
  { id: 'black_stained_glass_pane', name: 'Schwarze Glasscheibe', category: 'Glas' },
  
  // Terrakotta
  { id: 'terracotta', name: 'Terrakotta', category: 'Terrakotta' },
  { id: 'white_terracotta', name: 'Weiße Terrakotta', category: 'Terrakotta' },
  { id: 'orange_terracotta', name: 'Orange Terrakotta', category: 'Terrakotta' },
  { id: 'magenta_terracotta', name: 'Magenta Terrakotta', category: 'Terrakotta' },
  { id: 'light_blue_terracotta', name: 'Hellblaue Terrakotta', category: 'Terrakotta' },
  { id: 'yellow_terracotta', name: 'Gelbe Terrakotta', category: 'Terrakotta' },
  { id: 'lime_terracotta', name: 'Hellgrüne Terrakotta', category: 'Terrakotta' },
  { id: 'pink_terracotta', name: 'Rosa Terrakotta', category: 'Terrakotta' },
  { id: 'gray_terracotta', name: 'Graue Terrakotta', category: 'Terrakotta' },
  { id: 'light_gray_terracotta', name: 'Hellgraue Terrakotta', category: 'Terrakotta' },
  { id: 'cyan_terracotta', name: 'Türkise Terrakotta', category: 'Terrakotta' },
  { id: 'purple_terracotta', name: 'Violette Terrakotta', category: 'Terrakotta' },
  { id: 'blue_terracotta', name: 'Blaue Terrakotta', category: 'Terrakotta' },
  { id: 'brown_terracotta', name: 'Braune Terrakotta', category: 'Terrakotta' },
  { id: 'green_terracotta', name: 'Grüne Terrakotta', category: 'Terrakotta' },
  { id: 'red_terracotta', name: 'Rote Terrakotta', category: 'Terrakotta' },
  { id: 'black_terracotta', name: 'Schwarze Terrakotta', category: 'Terrakotta' },
  { id: 'white_glazed_terracotta', name: 'Weiße glasierte Terrakotta', category: 'Terrakotta' },
  { id: 'orange_glazed_terracotta', name: 'Orange glasierte Terrakotta', category: 'Terrakotta' },
  { id: 'magenta_glazed_terracotta', name: 'Magenta glasierte Terrakotta', category: 'Terrakotta' },
  { id: 'light_blue_glazed_terracotta', name: 'Hellblaue glasierte Terrakotta', category: 'Terrakotta' },
  { id: 'yellow_glazed_terracotta', name: 'Gelbe glasierte Terrakotta', category: 'Terrakotta' },
  { id: 'lime_glazed_terracotta', name: 'Hellgrüne glasierte Terrakotta', category: 'Terrakotta' },
  { id: 'pink_glazed_terracotta', name: 'Rosa glasierte Terrakotta', category: 'Terrakotta' },
  { id: 'gray_glazed_terracotta', name: 'Graue glasierte Terrakotta', category: 'Terrakotta' },
  { id: 'light_gray_glazed_terracotta', name: 'Hellgraue glasierte Terrakotta', category: 'Terrakotta' },
  { id: 'cyan_glazed_terracotta', name: 'Türkise glasierte Terrakotta', category: 'Terrakotta' },
  { id: 'purple_glazed_terracotta', name: 'Violette glasierte Terrakotta', category: 'Terrakotta' },
  { id: 'blue_glazed_terracotta', name: 'Blaue glasierte Terrakotta', category: 'Terrakotta' },
  { id: 'brown_glazed_terracotta', name: 'Braune glasierte Terrakotta', category: 'Terrakotta' },
  { id: 'green_glazed_terracotta', name: 'Grüne glasierte Terrakotta', category: 'Terrakotta' },
  { id: 'red_glazed_terracotta', name: 'Rote glasierte Terrakotta', category: 'Terrakotta' },
  { id: 'black_glazed_terracotta', name: 'Schwarze glasierte Terrakotta', category: 'Terrakotta' },
  
  // Wolle
  { id: 'white_wool', name: 'Weiße Wolle', category: 'Wolle' },
  { id: 'orange_wool', name: 'Orange Wolle', category: 'Wolle' },
  { id: 'magenta_wool', name: 'Magenta Wolle', category: 'Wolle' },
  { id: 'light_blue_wool', name: 'Hellblaue Wolle', category: 'Wolle' },
  { id: 'yellow_wool', name: 'Gelbe Wolle', category: 'Wolle' },
  { id: 'lime_wool', name: 'Hellgrüne Wolle', category: 'Wolle' },
  { id: 'pink_wool', name: 'Rosa Wolle', category: 'Wolle' },
  { id: 'gray_wool', name: 'Graue Wolle', category: 'Wolle' },
  { id: 'light_gray_wool', name: 'Hellgraue Wolle', category: 'Wolle' },
  { id: 'cyan_wool', name: 'Türkise Wolle', category: 'Wolle' },
  { id: 'purple_wool', name: 'Violette Wolle', category: 'Wolle' },
  { id: 'blue_wool', name: 'Blaue Wolle', category: 'Wolle' },
  { id: 'brown_wool', name: 'Braune Wolle', category: 'Wolle' },
  { id: 'green_wool', name: 'Grüne Wolle', category: 'Wolle' },
  { id: 'red_wool', name: 'Rote Wolle', category: 'Wolle' },
  { id: 'black_wool', name: 'Schwarze Wolle', category: 'Wolle' },
  { id: 'white_carpet', name: 'Weißer Teppich', category: 'Wolle' },
  { id: 'orange_carpet', name: 'Oranger Teppich', category: 'Wolle' },
  { id: 'magenta_carpet', name: 'Magenta Teppich', category: 'Wolle' },
  { id: 'light_blue_carpet', name: 'Hellblauer Teppich', category: 'Wolle' },
  { id: 'yellow_carpet', name: 'Gelber Teppich', category: 'Wolle' },
  { id: 'lime_carpet', name: 'Hellgrüner Teppich', category: 'Wolle' },
  { id: 'pink_carpet', name: 'Rosa Teppich', category: 'Wolle' },
  { id: 'gray_carpet', name: 'Grauer Teppich', category: 'Wolle' },
  { id: 'light_gray_carpet', name: 'Hellgrauer Teppich', category: 'Wolle' },
  { id: 'cyan_carpet', name: 'Türkiser Teppich', category: 'Wolle' },
  { id: 'purple_carpet', name: 'Violetter Teppich', category: 'Wolle' },
  { id: 'blue_carpet', name: 'Blauer Teppich', category: 'Wolle' },
  { id: 'brown_carpet', name: 'Brauner Teppich', category: 'Wolle' },
  { id: 'green_carpet', name: 'Grüner Teppich', category: 'Wolle' },
  { id: 'red_carpet', name: 'Roter Teppich', category: 'Wolle' },
  { id: 'black_carpet', name: 'Schwarzer Teppich', category: 'Wolle' },
  
  // Beton
  { id: 'white_concrete', name: 'Weißer Beton', category: 'Beton' },
  { id: 'orange_concrete', name: 'Oranger Beton', category: 'Beton' },
  { id: 'magenta_concrete', name: 'Magenta Beton', category: 'Beton' },
  { id: 'light_blue_concrete', name: 'Hellblauer Beton', category: 'Beton' },
  { id: 'yellow_concrete', name: 'Gelber Beton', category: 'Beton' },
  { id: 'lime_concrete', name: 'Hellgrüner Beton', category: 'Beton' },
  { id: 'pink_concrete', name: 'Rosa Beton', category: 'Beton' },
  { id: 'gray_concrete', name: 'Grauer Beton', category: 'Beton' },
  { id: 'light_gray_concrete', name: 'Hellgrauer Beton', category: 'Beton' },
  { id: 'cyan_concrete', name: 'Türkiser Beton', category: 'Beton' },
  { id: 'purple_concrete', name: 'Violetter Beton', category: 'Beton' },
  { id: 'blue_concrete', name: 'Blauer Beton', category: 'Beton' },
  { id: 'brown_concrete', name: 'Brauner Beton', category: 'Beton' },
  { id: 'green_concrete', name: 'Grüner Beton', category: 'Beton' },
  { id: 'red_concrete', name: 'Roter Beton', category: 'Beton' },
  { id: 'black_concrete', name: 'Schwarzer Beton', category: 'Beton' },
  { id: 'white_concrete_powder', name: 'Weißer Trockenbeton', category: 'Beton' },
  { id: 'orange_concrete_powder', name: 'Oranger Trockenbeton', category: 'Beton' },
  { id: 'magenta_concrete_powder', name: 'Magenta Trockenbeton', category: 'Beton' },
  { id: 'light_blue_concrete_powder', name: 'Hellblauer Trockenbeton', category: 'Beton' },
  { id: 'yellow_concrete_powder', name: 'Gelber Trockenbeton', category: 'Beton' },
  { id: 'lime_concrete_powder', name: 'Hellgrüner Trockenbeton', category: 'Beton' },
  { id: 'pink_concrete_powder', name: 'Rosa Trockenbeton', category: 'Beton' },
  { id: 'gray_concrete_powder', name: 'Grauer Trockenbeton', category: 'Beton' },
  { id: 'light_gray_concrete_powder', name: 'Hellgrauer Trockenbeton', category: 'Beton' },
  { id: 'cyan_concrete_powder', name: 'Türkiser Trockenbeton', category: 'Beton' },
  { id: 'purple_concrete_powder', name: 'Violetter Trockenbeton', category: 'Beton' },
  { id: 'blue_concrete_powder', name: 'Blauer Trockenbeton', category: 'Beton' },
  { id: 'brown_concrete_powder', name: 'Brauner Trockenbeton', category: 'Beton' },
  { id: 'green_concrete_powder', name: 'Grüner Trockenbeton', category: 'Beton' },
  { id: 'red_concrete_powder', name: 'Roter Trockenbeton', category: 'Beton' },
  { id: 'black_concrete_powder', name: 'Schwarzer Trockenbeton', category: 'Beton' },
  
  // Mob Drops
  { id: 'rotten_flesh', name: 'Verrottetes Fleisch', category: 'Mob Drops' },
  { id: 'bone', name: 'Knochen', category: 'Mob Drops' },
  { id: 'bone_meal', name: 'Knochenmehl', category: 'Mob Drops' },
  { id: 'gunpowder', name: 'Schwarzpulver', category: 'Mob Drops' },
  { id: 'string', name: 'Faden', category: 'Mob Drops' },
  { id: 'spider_eye', name: 'Spinnenauge', category: 'Mob Drops' },
  { id: 'ender_pearl', name: 'Enderperle', category: 'Mob Drops' },
  { id: 'blaze_rod', name: 'Lohenrute', category: 'Mob Drops' },
  { id: 'blaze_powder', name: 'Lohenstaub', category: 'Mob Drops' },
  { id: 'ghast_tear', name: 'Ghast-Träne', category: 'Mob Drops' },
  { id: 'magma_cream', name: 'Magmacreme', category: 'Mob Drops' },
  { id: 'slime_ball', name: 'Schleimball', category: 'Mob Drops' },
  { id: 'leather', name: 'Leder', category: 'Mob Drops' },
  { id: 'feather', name: 'Feder', category: 'Mob Drops' },
  { id: 'egg', name: 'Ei', category: 'Mob Drops' },
  { id: 'chicken_egg', name: 'Hühnerei', category: 'Mob Drops' },
  { id: 'rabbit_hide', name: 'Kaninchenfell', category: 'Mob Drops' },
  { id: 'rabbit_foot', name: 'Hasenpfote', category: 'Mob Drops' },
  { id: 'scute', name: 'Hornschild', category: 'Mob Drops' },
  { id: 'turtle_egg', name: 'Schildkrötenei', category: 'Mob Drops' },
  { id: 'shulker_shell', name: 'Shulker-Schale', category: 'Mob Drops' },
  { id: 'phantom_membrane', name: 'Phantomhaut', category: 'Mob Drops' },
  { id: 'nautilus_shell', name: 'Nautilusschale', category: 'Mob Drops' },
  { id: 'heart_of_the_sea', name: 'Herz des Meeres', category: 'Mob Drops' },
  { id: 'ink_sac', name: 'Tintenbeutel', category: 'Mob Drops' },
  { id: 'glow_ink_sac', name: 'Leucht-Tintenbeutel', category: 'Mob Drops' },
  { id: 'armadillo_scute', name: 'Gürteltier-Hornschild', category: 'Mob Drops' },
  { id: 'wolf_armor', name: 'Wolfsrüstung', category: 'Mob Drops' },
  { id: 'experience_bottle', name: 'Erfahrungsfläschchen', category: 'Mob Drops' },
  
  // Nahrung
  { id: 'apple', name: 'Apfel', category: 'Nahrung' },
  { id: 'golden_apple', name: 'Goldener Apfel', category: 'Nahrung' },
  { id: 'enchanted_golden_apple', name: 'Verzauberter goldener Apfel', category: 'Nahrung' },
  { id: 'bread', name: 'Brot', category: 'Nahrung' },
  { id: 'porkchop', name: 'Rohes Schweinefleisch', category: 'Nahrung' },
  { id: 'cooked_porkchop', name: 'Gebratenes Schweinefleisch', category: 'Nahrung' },
  { id: 'beef', name: 'Rohes Rindfleisch', category: 'Nahrung' },
  { id: 'cooked_beef', name: 'Steak', category: 'Nahrung' },
  { id: 'chicken', name: 'Rohes Hühnchen', category: 'Nahrung' },
  { id: 'cooked_chicken', name: 'Gebratenes Hühnchen', category: 'Nahrung' },
  { id: 'mutton', name: 'Rohes Hammelfleisch', category: 'Nahrung' },
  { id: 'cooked_mutton', name: 'Gebratenes Hammelfleisch', category: 'Nahrung' },
  { id: 'rabbit', name: 'Rohes Kaninchen', category: 'Nahrung' },
  { id: 'cooked_rabbit', name: 'Gebratenes Kaninchen', category: 'Nahrung' },
  { id: 'cod', name: 'Roher Kabeljau', category: 'Nahrung' },
  { id: 'cooked_cod', name: 'Gebratener Kabeljau', category: 'Nahrung' },
  { id: 'salmon', name: 'Roher Lachs', category: 'Nahrung' },
  { id: 'cooked_salmon', name: 'Gebratener Lachs', category: 'Nahrung' },
  { id: 'tropical_fish', name: 'Tropenfisch', category: 'Nahrung' },
  { id: 'pufferfish', name: 'Kugelfisch', category: 'Nahrung' },
  { id: 'cookie', name: 'Keks', category: 'Nahrung' },
  { id: 'melon_slice', name: 'Melonenscheibe', category: 'Nahrung' },
  { id: 'dried_kelp', name: 'Getrockneter Kelp', category: 'Nahrung' },
  { id: 'beef_stew', name: 'Rindereintopf', category: 'Nahrung' },
  { id: 'rabbit_stew', name: 'Kanincheneintopf', category: 'Nahrung' },
  { id: 'mushroom_stew', name: 'Pilzsuppe', category: 'Nahrung' },
  { id: 'beetroot_soup', name: 'Rote-Bete-Suppe', category: 'Nahrung' },
  { id: 'suspicious_stew', name: 'Seltsame Suppe', category: 'Nahrung' },
  { id: 'honey_bottle', name: 'Honigflasche', category: 'Nahrung' },
  { id: 'honeycomb', name: 'Honigwabe', category: 'Nahrung' },
  { id: 'honeycomb_block', name: 'Honigwabenblock', category: 'Nahrung' },
  { id: 'ominous_bottle', name: 'Unheilvolle Flasche', category: 'Nahrung' },
  { id: 'cake', name: 'Kuchen', category: 'Nahrung' },
  { id: 'pumpkin_pie', name: 'Kürbiskuchen', category: 'Nahrung' },
  
  // Werkzeuge & Waffen
  { id: 'wooden_pickaxe', name: 'Holzspitzhacke', category: 'Werkzeuge' },
  { id: 'stone_pickaxe', name: 'Steinspitzhacke', category: 'Werkzeuge' },
  { id: 'iron_pickaxe', name: 'Eisenspitzhacke', category: 'Werkzeuge' },
  { id: 'golden_pickaxe', name: 'Goldspitzhacke', category: 'Werkzeuge' },
  { id: 'diamond_pickaxe', name: 'Diamantspitzhacke', category: 'Werkzeuge' },
  { id: 'netherite_pickaxe', name: 'Netheritspitzhacke', category: 'Werkzeuge' },
  { id: 'wooden_axe', name: 'Holzaxt', category: 'Werkzeuge' },
  { id: 'stone_axe', name: 'Steinaxt', category: 'Werkzeuge' },
  { id: 'iron_axe', name: 'Eisenaxt', category: 'Werkzeuge' },
  { id: 'golden_axe', name: 'Goldaxt', category: 'Werkzeuge' },
  { id: 'diamond_axe', name: 'Diamantaxt', category: 'Werkzeuge' },
  { id: 'netherite_axe', name: 'Netheritaxt', category: 'Werkzeuge' },
  { id: 'wooden_shovel', name: 'Holzschaufel', category: 'Werkzeuge' },
  { id: 'stone_shovel', name: 'Steinschaufel', category: 'Werkzeuge' },
  { id: 'iron_shovel', name: 'Eisenschaufel', category: 'Werkzeuge' },
  { id: 'golden_shovel', name: 'Goldschaufel', category: 'Werkzeuge' },
  { id: 'diamond_shovel', name: 'Diamantschaufel', category: 'Werkzeuge' },
  { id: 'netherite_shovel', name: 'Neteritschaufel', category: 'Werkzeuge' },
  { id: 'wooden_hoe', name: 'Holzhacke', category: 'Werkzeuge' },
  { id: 'stone_hoe', name: 'Steinhacke', category: 'Werkzeuge' },
  { id: 'iron_hoe', name: 'Eisenhacke', category: 'Werkzeuge' },
  { id: 'golden_hoe', name: 'Goldhacke', category: 'Werkzeuge' },
  { id: 'diamond_hoe', name: 'Diamanthacke', category: 'Werkzeuge' },
  { id: 'netherite_hoe', name: 'Netherithacke', category: 'Werkzeuge' },
  { id: 'wooden_sword', name: 'Holzschwert', category: 'Werkzeuge' },
  { id: 'stone_sword', name: 'Steinschwert', category: 'Werkzeuge' },
  { id: 'iron_sword', name: 'Eisenschwert', category: 'Werkzeuge' },
  { id: 'golden_sword', name: 'Goldschwert', category: 'Werkzeuge' },
  { id: 'diamond_sword', name: 'Diamantschwert', category: 'Werkzeuge' },
  { id: 'netherite_sword', name: 'Neteritschwert', category: 'Werkzeuge' },
  { id: 'bow', name: 'Bogen', category: 'Werkzeuge' },
  { id: 'crossbow', name: 'Armbrust', category: 'Werkzeuge' },
  { id: 'trident', name: 'Dreizack', category: 'Werkzeuge' },
  { id: 'mace', name: 'Streitkolben', category: 'Werkzeuge' },
  { id: 'brush', name: 'Pinsel', category: 'Werkzeuge' },
  { id: 'shears', name: 'Schere', category: 'Werkzeuge' },
  { id: 'flint_and_steel', name: 'Feuerzeug', category: 'Werkzeuge' },
  { id: 'fishing_rod', name: 'Angel', category: 'Werkzeuge' },
  { id: 'carrot_on_a_stick', name: 'Karottenrute', category: 'Werkzeuge' },
  { id: 'warped_fungus_on_a_stick', name: 'Wirrpilzrute', category: 'Werkzeuge' },
  { id: 'lead', name: 'Leine', category: 'Werkzeuge' },
  { id: 'name_tag', name: 'Namensschild', category: 'Werkzeuge' },
  { id: 'saddle', name: 'Sattel', category: 'Werkzeuge' },
  { id: 'horse_armor_iron', name: 'Eisenpferderüstung', category: 'Werkzeuge' },
  { id: 'horse_armor_gold', name: 'Goldpferderüstung', category: 'Werkzeuge' },
  { id: 'horse_armor_diamond', name: 'Diamantpferderüstung', category: 'Werkzeuge' },
  { id: 'horse_armor_leather', name: 'Lederpferderüstung', category: 'Werkzeuge' },
  
  // Rüstung
  { id: 'leather_helmet', name: 'Lederkappe', category: 'Rüstung' },
  { id: 'leather_chestplate', name: 'Lederjacke', category: 'Rüstung' },
  { id: 'leather_leggings', name: 'Lederhose', category: 'Rüstung' },
  { id: 'leather_boots', name: 'Lederstiefel', category: 'Rüstung' },
  { id: 'chainmail_helmet', name: 'Kettenhaube', category: 'Rüstung' },
  { id: 'chainmail_chestplate', name: 'Kettenhemd', category: 'Rüstung' },
  { id: 'chainmail_leggings', name: 'Kettenbeinlinge', category: 'Rüstung' },
  { id: 'chainmail_boots', name: 'Kettenstiefel', category: 'Rüstung' },
  { id: 'iron_helmet', name: 'Eisenhelm', category: 'Rüstung' },
  { id: 'iron_chestplate', name: 'Eisenharnisch', category: 'Rüstung' },
  { id: 'iron_leggings', name: 'Eisenbeinlinge', category: 'Rüstung' },
  { id: 'iron_boots', name: 'Eisenstiefel', category: 'Rüstung' },
  { id: 'golden_helmet', name: 'Goldhelm', category: 'Rüstung' },
  { id: 'golden_chestplate', name: 'Goldharnisch', category: 'Rüstung' },
  { id: 'golden_leggings', name: 'Goldbeinlinge', category: 'Rüstung' },
  { id: 'golden_boots', name: 'Goldstiefel', category: 'Rüstung' },
  { id: 'diamond_helmet', name: 'Diamanthelm', category: 'Rüstung' },
  { id: 'diamond_chestplate', name: 'Diamantharnisch', category: 'Rüstung' },
  { id: 'diamond_leggings', name: 'Diamantbeinlinge', category: 'Rüstung' },
  { id: 'diamond_boots', name: 'Diamantstiefel', category: 'Rüstung' },
  { id: 'netherite_helmet', name: 'Netherithelm', category: 'Rüstung' },
  { id: 'netherite_chestplate', name: 'Netheritharnisch', category: 'Rüstung' },
  { id: 'netherite_leggings', name: 'Netheritbeinlinge', category: 'Rüstung' },
  { id: 'netherite_boots', name: 'Netheritstiefel', category: 'Rüstung' },
  { id: 'turtle_helmet', name: 'Schildkrötenpanzer', category: 'Rüstung' },
  { id: 'elytra', name: 'Elytren', category: 'Rüstung' },
  
  // Sonstiges
  { id: 'stick', name: 'Stock', category: 'Sonstiges' },
  { id: 'bowl', name: 'Schüssel', category: 'Sonstiges' },
  { id: 'flint', name: 'Feuerstein', category: 'Sonstiges' },
  { id: 'brick', name: 'Ziegel', category: 'Sonstiges' },
  { id: 'nether_brick', name: 'Netherziegel', category: 'Sonstiges' },
  { id: 'paper', name: 'Papier', category: 'Sonstiges' },
  { id: 'book', name: 'Buch', category: 'Sonstiges' },
  { id: 'writable_book', name: 'Buch und Feder', category: 'Sonstiges' },
  { id: 'enchanted_book', name: 'Verzaubertes Buch', category: 'Sonstiges' },
  { id: 'ender_eye', name: 'Enderauge', category: 'Sonstiges' },
  { id: 'ender_chest', name: 'Endertruhe', category: 'Sonstiges' },
  { id: 'end_portal_frame', name: 'Endportalrahmen', category: 'Sonstiges' },
  { id: 'beacon', name: 'Leuchtfeuer', category: 'Sonstiges' },
  { id: 'conduit', name: 'Aquisator', category: 'Sonstiges' },
  { id: 'lodestone', name: 'Leitstein', category: 'Sonstiges' },
  { id: 'recovery_compass', name: 'Wiederbeschaffungskompass', category: 'Sonstiges' },
  { id: 'totem_of_undying', name: 'Totem der Unsterblichkeit', category: 'Sonstiges' },
  { id: 'disc_fragment_5', name: 'Schallplattenfragment', category: 'Sonstiges' },
  { id: 'music_disc_13', name: 'Schallplatte 13', category: 'Sonstiges' },
  { id: 'music_disc_cat', name: 'Schallplatte Cat', category: 'Sonstiges' },
  { id: 'music_disc_blocks', name: 'Schallplatte Blocks', category: 'Sonstiges' },
  { id: 'music_disc_chirp', name: 'Schallplatte Chirp', category: 'Sonstiges' },
  { id: 'music_disc_far', name: 'Schallplatte Far', category: 'Sonstiges' },
  { id: 'music_disc_mall', name: 'Schallplatte Mall', category: 'Sonstiges' },
  { id: 'music_disc_mellohi', name: 'Schallplatte Mellohi', category: 'Sonstiges' },
  { id: 'music_disc_stal', name: 'Schallplatte Stal', category: 'Sonstiges' },
  { id: 'music_disc_strad', name: 'Schallplatte Strad', category: 'Sonstiges' },
  { id: 'music_disc_ward', name: 'Schallplatte Ward', category: 'Sonstiges' },
  { id: 'music_disc_11', name: 'Schallplatte 11', category: 'Sonstiges' },
  { id: 'music_disc_wait', name: 'Schallplatte Wait', category: 'Sonstiges' },
  { id: 'music_disc_otherside', name: 'Schallplatte Otherside', category: 'Sonstiges' },
  { id: 'music_disc_relic', name: 'Schallplatte Relic', category: 'Sonstiges' },
  { id: 'music_disc_5', name: 'Schallplatte 5', category: 'Sonstiges' },
  { id: 'music_disc_pigstep', name: 'Schallplatte Pigstep', category: 'Sonstiges' },
  { id: 'music_disc_creator', name: 'Schallplatte Creator', category: 'Sonstiges' },
  { id: 'music_disc_creator_music_box', name: 'Schallplatte Creator Music Box', category: 'Sonstiges' },
  { id: 'music_disc_precipice', name: 'Schallplatte Precipice', category: 'Sonstiges' },
  { id: 'trial_key', name: 'Prüfungs-Schlüssel', category: 'Sonstiges' },
  { id: 'ominous_trial_key', name: 'Unheilvoller Prüfungs-Schlüssel', category: 'Sonstiges' },
  { id: 'wind_charge', name: 'Windauftrag', category: 'Sonstiges' },
  { id: 'heavy_core', name: 'Schwerer Kern', category: 'Sonstiges' },
  { id: 'breeze_rod', name: 'Brise-Rute', category: 'Sonstiges' },
  { id: 'vault', name: 'Tresor', category: 'Sonstiges' },
  { id: 'ominous_vault', name: 'Unheilvoller Tresor', category: 'Sonstiges' },
  { id: 'trial_spawner', name: 'Prüfungs-Spawner', category: 'Sonstiges' },
  { id: 'ominous_trial_spawner', name: 'Unheilvoller Prüfungs-Spawner', category: 'Sonstiges' },
  { id: 'crafter', name: 'Werker', category: 'Sonstiges' },
  { id: 'copper_grate', name: 'Kupfergitter', category: 'Sonstiges' },
  { id: 'exposed_copper_grate', name: 'Angelaufenes Kupfergitter', category: 'Sonstiges' },
  { id: 'weathered_copper_grate', name: 'Verwittertes Kupfergitter', category: 'Sonstiges' },
  { id: 'oxidized_copper_grate', name: 'Oxidiertes Kupfergitter', category: 'Sonstiges' },
  { id: 'waxed_copper_grate', name: 'Gewachstes Kupfergitter', category: 'Sonstiges' },
  { id: 'waxed_exposed_copper_grate', name: 'Gewachstes angelaufenes Kupfergitter', category: 'Sonstiges' },
  { id: 'waxed_weathered_copper_grate', name: 'Gewachstes verwittertes Kupfergitter', category: 'Sonstiges' },
  { id: 'waxed_oxidized_copper_grate', name: 'Gewachstes oxidiertes Kupfergitter', category: 'Sonstiges' },
  { id: 'copper_bulb', name: 'Kupferlampe', category: 'Sonstiges' },
  { id: 'exposed_copper_bulb', name: 'Angelaufene Kupferlampe', category: 'Sonstiges' },
  { id: 'weathered_copper_bulb', name: 'Verwitterte Kupferlampe', category: 'Sonstiges' },
  { id: 'oxidized_copper_bulb', name: 'Oxidierte Kupferlampe', category: 'Sonstiges' },
  { id: 'waxed_copper_bulb', name: 'Gewachste Kupferlampe', category: 'Sonstiges' },
  { id: 'waxed_exposed_copper_bulb', name: 'Gewachste angelaufene Kupferlampe', category: 'Sonstiges' },
  { id: 'waxed_weathered_copper_bulb', name: 'Gewachste verwitterte Kupferlampe', category: 'Sonstiges' },
  { id: 'waxed_oxidized_copper_bulb', name: 'Gewachste oxidierte Kupferlampe', category: 'Sonstiges' },
  { id: 'copper_door', name: 'Kupfertür', category: 'Sonstiges' },
  { id: 'exposed_copper_door', name: 'Angelaufene Kupfertür', category: 'Sonstiges' },
  { id: 'weathered_copper_door', name: 'Verwitterte Kupfertür', category: 'Sonstiges' },
  { id: 'oxidized_copper_door', name: 'Oxidierte Kupfertür', category: 'Sonstiges' },
  { id: 'waxed_copper_door', name: 'Gewachste Kupfertür', category: 'Sonstiges' },
  { id: 'waxed_exposed_copper_door', name: 'Gewachste angelaufene Kupfertür', category: 'Sonstiges' },
  { id: 'waxed_weathered_copper_door', name: 'Gewachste verwitterte Kupfertür', category: 'Sonstiges' },
  { id: 'waxed_oxidized_copper_door', name: 'Gewachste oxidierte Kupfertür', category: 'Sonstiges' },
  { id: 'copper_trapdoor', name: 'Kupferfalltür', category: 'Sonstiges' },
  { id: 'exposed_copper_trapdoor', name: 'Angelaufene Kupferfalltür', category: 'Sonstiges' },
  { id: 'weathered_copper_trapdoor', name: 'Verwitterte Kupferfalltür', category: 'Sonstiges' },
  { id: 'oxidized_copper_trapdoor', name: 'Oxidierte Kupferfalltür', category: 'Sonstiges' },
  { id: 'waxed_copper_trapdoor', name: 'Gewachste Kupferfalltür', category: 'Sonstiges' },
  { id: 'waxed_exposed_copper_trapdoor', name: 'Gewachste angelaufene Kupferfalltür', category: 'Sonstiges' },
  { id: 'waxed_weathered_copper_trapdoor', name: 'Gewachste verwitterte Kupferfalltür', category: 'Sonstiges' },
  { id: 'waxed_oxidized_copper_trapdoor', name: 'Gewachste oxidierte Kupferfalltür', category: 'Sonstiges' },
  { id: 'chiseled_copper', name: 'Gemeißelter Kupferblock', category: 'Sonstiges' },
  { id: 'exposed_chiseled_copper', name: 'Angelaufener gemeißelter Kupferblock', category: 'Sonstiges' },
  { id: 'weathered_chiseled_copper', name: 'Verwitterter gemeißelter Kupferblock', category: 'Sonstiges' },
  { id: 'oxidized_chiseled_copper', name: 'Oxidierter gemeißelter Kupferblock', category: 'Sonstiges' },
  { id: 'waxed_chiseled_copper', name: 'Gewachster gemeißelter Kupferblock', category: 'Sonstiges' },
  { id: 'waxed_exposed_chiseled_copper', name: 'Gewachster angelaufener gemeißelter Kupferblock', category: 'Sonstiges' },
  { id: 'waxed_weathered_chiseled_copper', name: 'Gewachster verwitterter gemeißelter Kupferblock', category: 'Sonstiges' },
  { id: 'waxed_oxidized_chiseled_copper', name: 'Gewachster oxidierter gemeißelter Kupferblock', category: 'Sonstiges' },
  { id: 'copper_block', name: 'Kupferblock', category: 'Sonstiges' },
  { id: 'exposed_copper', name: 'Angelaufener Kupferblock', category: 'Sonstiges' },
  { id: 'weathered_copper', name: 'Verwitterter Kupferblock', category: 'Sonstiges' },
  { id: 'oxidized_copper', name: 'Oxidierter Kupferblock', category: 'Sonstiges' },
  { id: 'waxed_copper_block', name: 'Gewachster Kupferblock', category: 'Sonstiges' },
  { id: 'waxed_exposed_copper', name: 'Gewachster angelaufener Kupferblock', category: 'Sonstiges' },
  { id: 'waxed_weathered_copper', name: 'Gewachster verwitterter Kupferblock', category: 'Sonstiges' },
  { id: 'waxed_oxidized_copper', name: 'Gewachster oxidierter Kupferblock', category: 'Sonstiges' },
  { id: 'cut_copper', name: 'Geschnittener Kupferblock', category: 'Sonstiges' },
  { id: 'exposed_cut_copper', name: 'Angelaufener geschnittener Kupferblock', category: 'Sonstiges' },
  { id: 'weathered_cut_copper', name: 'Verwitterter geschnittener Kupferblock', category: 'Sonstiges' },
  { id: 'oxidized_cut_copper', name: 'Oxidierter geschnittener Kupferblock', category: 'Sonstiges' },
  { id: 'waxed_cut_copper', name: 'Gewachster geschnittener Kupferblock', category: 'Sonstiges' },
  { id: 'waxed_exposed_cut_copper', name: 'Gewachster angelaufener geschnittener Kupferblock', category: 'Sonstiges' },
  { id: 'waxed_weathered_cut_copper', name: 'Gewachster verwitterter geschnittener Kupferblock', category: 'Sonstiges' },
  { id: 'waxed_oxidized_cut_copper', name: 'Gewachster oxidierter geschnittener Kupferblock', category: 'Sonstiges' },
  { id: 'cut_copper_stairs', name: 'Geschnittene Kupfertreppe', category: 'Sonstiges' },
  { id: 'exposed_cut_copper_stairs', name: 'Angelaufene geschnittene Kupfertreppe', category: 'Sonstiges' },
  { id: 'weathered_cut_copper_stairs', name: 'Verwitterte geschnittene Kupfertreppe', category: 'Sonstiges' },
  { id: 'oxidized_cut_copper_stairs', name: 'Oxidierte geschnittene Kupfertreppe', category: 'Sonstiges' },
  { id: 'waxed_cut_copper_stairs', name: 'Gewachste geschnittene Kupfertreppe', category: 'Sonstiges' },
  { id: 'waxed_exposed_cut_copper_stairs', name: 'Gewachste angelaufene geschnittene Kupfertreppe', category: 'Sonstiges' },
  { id: 'waxed_weathered_cut_copper_stairs', name: 'Gewachste verwitterte geschnittene Kupfertreppe', category: 'Sonstiges' },
  { id: 'waxed_oxidized_cut_copper_stairs', name: 'Gewachste oxidierte geschnittene Kupfertreppe', category: 'Sonstiges' },
  { id: 'cut_copper_slab', name: 'Geschnittene Kupferstufe', category: 'Sonstiges' },
  { id: 'exposed_cut_copper_slab', name: 'Angelaufene geschnittene Kupferstufe', category: 'Sonstiges' },
  { id: 'weathered_cut_copper_slab', name: 'Verwitterte geschnittene Kupferstufe', category: 'Sonstiges' },
  { id: 'oxidized_cut_copper_slab', name: 'Oxidierte geschnittene Kupferstufe', category: 'Sonstiges' },
  { id: 'waxed_cut_copper_slab', name: 'Gewachste geschnittene Kupferstufe', category: 'Sonstiges' },
  { id: 'waxed_exposed_cut_copper_slab', name: 'Gewachste angelaufene geschnittene Kupferstufe', category: 'Sonstiges' },
  { id: 'waxed_weathered_cut_copper_slab', name: 'Gewachste verwitterte geschnittene Kupferstufe', category: 'Sonstiges' },
  { id: 'waxed_oxidized_cut_copper_slab', name: 'Gewachste oxidierte geschnittene Kupferstufe', category: 'Sonstiges' },
];

export const BLOCK_CATEGORIES = Array.from(new Set(MINECRAFT_BLOCKS.map(b => b.category)));

export const getBlocksByCategory = (category: string): MinecraftBlock[] => {
  return MINECRAFT_BLOCKS.filter(block => block.category === category);
};

export const getBlockById = (id: string): MinecraftBlock | undefined => {
  return MINECRAFT_BLOCKS.find(block => block.id === id);
};
