export type UserRole = 'admin' | 'farmer' | 'viewer';

export interface User {
  id: string;
  username: string;
  role: UserRole;
  createdAt: string;
  createdBy?: string;
}

export interface OrderItem {
  blockId: string;
  amount: number;
  unit: 'dk' | 'kisten';
}

export interface UserOrderProgress {
  userId: string;
  status: 'accepted' | 'in_progress' | 'submitted' | 'confirmed';
  completedItems: { blockId: string; amount: number }[];
  submittedAt?: string;
  confirmedAt?: string;
  confirmedBy?: string;
}

export interface FarmOrder {
  id: string;
  items: OrderItem[];
  startDate: string;
  deadline: string;
  status: 'open' | 'in_progress' | 'completed';
  autoAssign: boolean;
  createdBy: string;
  createdAt: string;
  notes?: string;
  userProgress: UserOrderProgress[];
}

export interface AbsenceRequest {
  id: string;
  userId: string;
  username: string;
  startDate: string;
  endDate: string;
  reason: string;
  status: 'pending' | 'approved' | 'rejected';
  requestedAt: string;
}

export interface MinecraftBlock {
  id: string;
  name: string;
  category: string;
}

export const MINECRAFT_BLOCKS: MinecraftBlock[] = [
  // Baublöcke
  { id: 'stone', name: 'Stein', category: 'Baublöcke' },
  { id: 'granite', name: 'Granit', category: 'Baublöcke' },
  { id: 'diorite', name: 'Diorit', category: 'Baublöcke' },
  { id: 'andesite', name: 'Andesit', category: 'Baublöcke' },
  { id: 'cobblestone', name: 'Bruchstein', category: 'Baublöcke' },
  { id: 'mossy_cobblestone', name: 'Bemooster Bruchstein', category: 'Baublöcke' },
  { id: 'smooth_stone', name: 'Glatter Stein', category: 'Baublöcke' },
  { id: 'stone_bricks', name: 'Steinziegel', category: 'Baublöcke' },
  { id: 'mossy_stone_bricks', name: 'Bemooste Steinziegel', category: 'Baublöcke' },
  { id: 'cracked_stone_bricks', name: 'Rissige Steinziegel', category: 'Baublöcke' },
  { id: 'chiseled_stone_bricks', name: 'Gemeißelte Steinziegel', category: 'Baublöcke' },
  { id: 'bricks', name: 'Ziegel', category: 'Baublöcke' },
  { id: 'deepslate', name: 'Tiefenschiefer', category: 'Baublöcke' },
  { id: 'cobbled_deepslate', name: 'Bruchtiefenschiefer', category: 'Baublöcke' },
  { id: 'polished_deepslate', name: 'Polierter Tiefenschiefer', category: 'Baublöcke' },
  { id: 'deepslate_bricks', name: 'Tiefenschieferziegel', category: 'Baublöcke' },
  { id: 'deepslate_tiles', name: 'Tiefenschieferfliesen', category: 'Baublöcke' },
  { id: 'reinforced_deepslate', name: 'Verstärkter Tiefenschiefer', category: 'Baublöcke' },
  
  // Holz
  { id: 'oak_planks', name: 'Eichenholzbretter', category: 'Holz' },
  { id: 'spruce_planks', name: 'Fichtenholzbretter', category: 'Holz' },
  { id: 'birch_planks', name: 'Birkenholzbretter', category: 'Holz' },
  { id: 'jungle_planks', name: 'Tropenholzbretter', category: 'Holz' },
  { id: 'acacia_planks', name: 'Akazienholzbretter', category: 'Holz' },
  { id: 'dark_oak_planks', name: 'Schwarzeichenholzbretter', category: 'Holz' },
  { id: 'mangrove_planks', name: 'Mangrovenholzbretter', category: 'Holz' },
  { id: 'cherry_planks', name: 'Kirschholzbretter', category: 'Holz' },
  { id: 'bamboo_planks', name: 'Bambusbretter', category: 'Holz' },
  { id: 'crimson_planks', name: 'Karmesinbretter', category: 'Holz' },
  { id: 'warped_planks', name: 'Wirrbretter', category: 'Holz' },
  { id: 'oak_log', name: 'Eichenstamm', category: 'Holz' },
  { id: 'spruce_log', name: 'Fichtenstamm', category: 'Holz' },
  { id: 'birch_log', name: 'Birkenstamm', category: 'Holz' },
  { id: 'jungle_log', name: 'Tropenstamm', category: 'Holz' },
  { id: 'acacia_log', name: 'Akazienstamm', category: 'Holz' },
  { id: 'dark_oak_log', name: 'Schwarzeichenstamm', category: 'Holz' },
  { id: 'mangrove_log', name: 'Mangrovenstamm', category: 'Holz' },
  { id: 'cherry_log', name: 'Kirschstamm', category: 'Holz' },
  { id: 'bamboo_block', name: 'Bambusblock', category: 'Holz' },
  { id: 'crimson_stem', name: 'Karmesinstamm', category: 'Holz' },
  { id: 'warped_stem', name: 'Wirrstamm', category: 'Holz' },
  
  // Erze
  { id: 'coal_ore', name: 'Kohleerz', category: 'Erze' },
  { id: 'deepslate_coal_ore', name: 'Tiefenschiefer-Kohleerz', category: 'Erze' },
  { id: 'iron_ore', name: 'Eisenerz', category: 'Erze' },
  { id: 'deepslate_iron_ore', name: 'Tiefenschiefer-Eisenerz', category: 'Erze' },
  { id: 'copper_ore', name: 'Kupfererz', category: 'Erze' },
  { id: 'deepslate_copper_ore', name: 'Tiefenschiefer-Kupfererz', category: 'Erze' },
  { id: 'gold_ore', name: 'Golderz', category: 'Erze' },
  { id: 'deepslate_gold_ore', name: 'Tiefenschiefer-Golderz', category: 'Erze' },
  { id: 'redstone_ore', name: 'Redstone-Erz', category: 'Erze' },
  { id: 'deepslate_redstone_ore', name: 'Tiefenschiefer-Redstone-Erz', category: 'Erze' },
  { id: 'emerald_ore', name: 'Smaragderz', category: 'Erze' },
  { id: 'deepslate_emerald_ore', name: 'Tiefenschiefer-Smaragderz', category: 'Erze' },
  { id: 'lapis_ore', name: 'Lapislazulierz', category: 'Erze' },
  { id: 'deepslate_lapis_ore', name: 'Tiefenschiefer-Lapislazulierz', category: 'Erze' },
  { id: 'diamond_ore', name: 'Diamanterz', category: 'Erze' },
  { id: 'deepslate_diamond_ore', name: 'Tiefenschiefer-Diamanterz', category: 'Erze' },
  { id: 'nether_gold_ore', name: 'Nether-Golderz', category: 'Erze' },
  { id: 'ancient_debris', name: 'Antiker Schrott', category: 'Erze' },
  
  // Mineralien
  { id: 'coal_block', name: 'Kohleblock', category: 'Mineralien' },
  { id: 'iron_block', name: 'Eisenblock', category: 'Mineralien' },
  { id: 'copper_block', name: 'Kupferblock', category: 'Mineralien' },
  { id: 'gold_block', name: 'Goldblock', category: 'Mineralien' },
  { id: 'redstone_block', name: 'Redstone-Block', category: 'Mineralien' },
  { id: 'emerald_block', name: 'Smaragdblock', category: 'Mineralien' },
  { id: 'lapis_block', name: 'Lapislazuliblock', category: 'Mineralien' },
  { id: 'diamond_block', name: 'Diamantblock', category: 'Mineralien' },
  { id: 'netherite_block', name: 'Netheritblock', category: 'Mineralien' },
  { id: 'raw_iron_block', name: 'Roh Eisenblock', category: 'Mineralien' },
  { id: 'raw_copper_block', name: 'Roh Kupferblock', category: 'Mineralien' },
  { id: 'raw_gold_block', name: 'Roh Goldblock', category: 'Mineralien' },
  
  // Quartz
  { id: 'quartz_block', name: 'Quarzblock', category: 'Quartz' },
  { id: 'chiseled_quartz_block', name: 'Gemeißelter Quarzblock', category: 'Quartz' },
  { id: 'quartz_pillar', name: 'Quarzsäule', category: 'Quartz' },
  { id: 'quartz_bricks', name: 'Quarzziegel', category: 'Quartz' },
  { id: 'smooth_quartz', name: 'Glatter Quarz', category: 'Quartz' },
  { id: 'quartz_slab', name: 'Quarzstufe', category: 'Quartz' },
  { id: 'quartz_stairs', name: 'Quarztreppe', category: 'Quartz' },
  { id: 'nether_quartz_ore', name: 'Nether-Quarzerz', category: 'Quartz' },
  
  // Nether
  { id: 'netherrack', name: 'Netherrack', category: 'Nether' },
  { id: 'soul_sand', name: 'Seelensand', category: 'Nether' },
  { id: 'soul_soil', name: 'Seelenerde', category: 'Nether' },
  { id: 'basalt', name: 'Basalt', category: 'Nether' },
  { id: 'smooth_basalt', name: 'Glatter Basalt', category: 'Nether' },
  { id: 'polished_basalt', name: 'Polierter Basalt', category: 'Nether' },
  { id: 'blackstone', name: 'Schwarzstein', category: 'Nether' },
  { id: 'gilded_blackstone', name: 'Vergoldeter Schwarzstein', category: 'Nether' },
  { id: 'polished_blackstone', name: 'Polierter Schwarzstein', category: 'Nether' },
  { id: 'polished_blackstone_bricks', name: 'Polierte Schwarzsteinziegel', category: 'Nether' },
  { id: 'cracked_polished_blackstone_bricks', name: 'Rissige polierte Schwarzsteinziegel', category: 'Nether' },
  { id: 'chiseled_polished_blackstone', name: 'Gemeißelter polierter Schwarzstein', category: 'Nether' },
  { id: 'nether_bricks', name: 'Netherziegel', category: 'Nether' },
  { id: 'red_nether_bricks', name: 'Rote Netherziegel', category: 'Nether' },
  { id: 'cracked_nether_bricks', name: 'Rissige Netherziegel', category: 'Nether' },
  { id: 'chiseled_nether_bricks', name: 'Gemeißelte Netherziegel', category: 'Nether' },
  { id: 'magma_block', name: 'Magmablock', category: 'Nether' },
  { id: 'glowstone', name: 'Glowstone', category: 'Nether' },
  { id: 'shroomlight', name: 'Pilzlicht', category: 'Nether' },
  { id: 'warped_nylium', name: 'Wirr-Nezel', category: 'Nether' },
  { id: 'crimson_nylium', name: 'Karmesin-Nezel', category: 'Nether' },
  { id: 'warped_wart_block', name: 'Wirrwarzenblock', category: 'Nether' },
  { id: 'nether_wart_block', name: 'Netherwarzenblock', category: 'Nether' },
  
  // End
  { id: 'end_stone', name: 'Endstein', category: 'End' },
  { id: 'end_stone_bricks', name: 'Endsteinziegel', category: 'End' },
  { id: 'purpur_block', name: 'Purpurblock', category: 'End' },
  { id: 'purpur_pillar', name: 'Purpursäule', category: 'End' },
  { id: 'end_rod', name: 'Endstab', category: 'End' },
  { id: 'dragon_egg', name: 'Drachenei', category: 'End' },
  { id: 'obsidian', name: 'Obsidian', category: 'End' },
  { id: 'crying_obsidian', name: 'Weinender Obsidian', category: 'End' },
  
  // Natur
  { id: 'grass_block', name: 'Grasblock', category: 'Natur' },
  { id: 'dirt', name: 'Erde', category: 'Natur' },
  { id: 'coarse_dirt', name: 'Grobe Erde', category: 'Natur' },
  { id: 'podzol', name: 'Podsol', category: 'Natur' },
  { id: 'rooted_dirt', name: 'Bewurzelte Erde', category: 'Natur' },
  { id: 'moss_block', name: 'Moosblock', category: 'Natur' },
  { id: 'moss_carpet', name: 'Mosteppich', category: 'Natur' },
  { id: 'sand', name: 'Sand', category: 'Natur' },
  { id: 'red_sand', name: 'Roter Sand', category: 'Natur' },
  { id: 'gravel', name: 'Kies', category: 'Natur' },
  { id: 'clay', name: 'Ton', category: 'Natur' },
  { id: 'soul_torch', name: 'Seelenfackel', category: 'Natur' },
  { id: 'torch', name: 'Fackel', category: 'Natur' },
  { id: 'lantern', name: 'Laterne', category: 'Natur' },
  { id: 'soul_lantern', name: 'Seelenlaterne', category: 'Natur' },
  { id: 'sea_lantern', name: 'Seelaterne', category: 'Natur' },
  { id: 'glow_lichen', name: 'Leuchtflechte', category: 'Natur' },
  { id: 'sculk', name: 'Sculk', category: 'Natur' },
  { id: 'sculk_catalyst', name: 'Sculk-Katalysator', category: 'Natur' },
  { id: 'sculk_shrieker', name: 'Sculk-Kreischer', category: 'Natur' },
  { id: 'sculk_sensor', name: 'Sculk-Sensor', category: 'Natur' },
  
  // Pflanzen
  { id: 'oak_leaves', name: 'Eichenlaub', category: 'Pflanzen' },
  { id: 'spruce_leaves', name: 'Fichtenlaub', category: 'Pflanzen' },
  { id: 'birch_leaves', name: 'Birkenlaub', category: 'Pflanzen' },
  { id: 'jungle_leaves', name: 'Tropenlaub', category: 'Pflanzen' },
  { id: 'acacia_leaves', name: 'Akazienlaub', category: 'Pflanzen' },
  { id: 'dark_oak_leaves', name: 'Schwarzeichenlaub', category: 'Pflanzen' },
  { id: 'mangrove_leaves', name: 'Mangrovenlaub', category: 'Pflanzen' },
  { id: 'cherry_leaves', name: 'Kirschlaub', category: 'Pflanzen' },
  { id: 'azalea_leaves', name: 'Azaleenlaub', category: 'Pflanzen' },
  { id: 'flowering_azalea_leaves', name: 'Blühendes Azaleenlaub', category: 'Pflanzen' },
  { id: 'oak_sapling', name: 'Eichensetzling', category: 'Pflanzen' },
  { id: 'spruce_sapling', name: 'Fichtensetzling', category: 'Pflanzen' },
  { id: 'birch_sapling', name: 'Birkensetzling', category: 'Pflanzen' },
  { id: 'jungle_sapling', name: 'Tropensetzling', category: 'Pflanzen' },
  { id: 'acacia_sapling', name: 'Akaziensetzling', category: 'Pflanzen' },
  { id: 'dark_oak_sapling', name: 'Schwarzeichensetzling', category: 'Pflanzen' },
  { id: 'mangrove_propagule', name: 'Mangrovenkeimling', category: 'Pflanzen' },
  { id: 'cherry_sapling', name: 'Kirschsetzling', category: 'Pflanzen' },
  { id: 'azalea', name: 'Azalee', category: 'Pflanzen' },
  { id: 'flowering_azalea', name: 'Blühende Azalee', category: 'Pflanzen' },
  { id: 'cactus', name: 'Kaktus', category: 'Pflanzen' },
  { id: 'sugar_cane', name: 'Zuckerrohr', category: 'Pflanzen' },
  { id: 'bamboo', name: 'Bambus', category: 'Pflanzen' },
  { id: 'wheat', name: 'Weizen', category: 'Pflanzen' },
  { id: 'carrots', name: 'Karotten', category: 'Pflanzen' },
  { id: 'potatoes', name: 'Kartoffeln', category: 'Pflanzen' },
  { id: 'beetroots', name: 'Rote Bete', category: 'Pflanzen' },
  { id: 'melon', name: 'Melone', category: 'Pflanzen' },
  { id: 'pumpkin', name: 'Kürbis', category: 'Pflanzen' },
  { id: 'carved_pumpkin', name: 'Geschnitzter Kürbis', category: 'Pflanzen' },
  { id: 'jack_o_lantern', name: 'Kürbislaterne', category: 'Pflanzen' },
  { id: 'melon_slice', name: 'Melonenscheibe', category: 'Pflanzen' },
  { id: 'sweet_berries', name: 'Süßbeeren', category: 'Pflanzen' },
  { id: 'glow_berries', name: 'Leuchtbeeren', category: 'Pflanzen' },
  { id: 'cocoa_beans', name: 'Kakaobohnen', category: 'Pflanzen' },
  { id: 'nether_wart', name: 'Netherwarze', category: 'Pflanzen' },
  { id: 'lily_pad', name: 'Seerosenblatt', category: 'Pflanzen' },
  { id: 'vine', name: 'Ranken', category: 'Pflanzen' },
  { id: 'weeping_vines', name: 'Trauerranken', category: 'Pflanzen' },
  { id: 'twisting_vines', name: 'Zwirbelranken', category: 'Pflanzen' },
  { id: 'cave_vines', name: 'Höhlenranken', category: 'Pflanzen' },
  { id: 'big_dripleaf', name: 'Großes Tropfblatt', category: 'Pflanzen' },
  { id: 'small_dripleaf', name: 'Kleines Tropfblatt', category: 'Pflanzen' },
  { id: 'spore_blossom', name: 'Sporenblüte', category: 'Pflanzen' },
  { id: 'hanging_roots', name: 'Hängende Wurzeln', category: 'Pflanzen' },
  { id: 'dried_kelp_block', name: 'Getrockneter Kelpblock', category: 'Pflanzen' },
  { id: 'hay_block', name: 'Heuballen', category: 'Pflanzen' },
  { id: 'sponge', name: 'Schwamm', category: 'Pflanzen' },
  { id: 'wet_sponge', name: 'Nasser Schwamm', category: 'Pflanzen' },
  
  // Blumen
  { id: 'dandelion', name: 'Löwenzahn', category: 'Blumen' },
  { id: 'poppy', name: 'Mohn', category: 'Blumen' },
  { id: 'blue_orchid', name: 'Blaue Orchidee', category: 'Blumen' },
  { id: 'allium', name: 'Allium', category: 'Blumen' },
  { id: 'azure_bluet', name: 'Azurblau', category: 'Blumen' },
  { id: 'red_tulip', name: 'Rote Tulpe', category: 'Blumen' },
  { id: 'orange_tulip', name: 'Orange Tulpe', category: 'Blumen' },
  { id: 'white_tulip', name: 'Weiße Tulpe', category: 'Blumen' },
  { id: 'pink_tulip', name: 'Rosa Tulpe', category: 'Blumen' },
  { id: 'oxeye_daisy', name: 'Margerite', category: 'Blumen' },
  { id: 'cornflower', name: 'Kornblume', category: 'Blumen' },
  { id: 'lily_of_the_valley', name: 'Maiglöckchen', category: 'Blumen' },
  { id: 'sunflower', name: 'Sonnenblume', category: 'Blumen' },
  { id: 'lilac', name: 'Flieder', category: 'Blumen' },
  { id: 'rose_bush', name: 'Rosenstrauch', category: 'Blumen' },
  { id: 'peony', name: 'Pfingstrose', category: 'Blumen' },
  { id: 'wither_rose', name: 'Witherrose', category: 'Blumen' },
  { id: 'pink_petals', name: 'Rosa Blütenblätter', category: 'Blumen' },
  { id: 'chorus_flower', name: 'Chorusblüte', category: 'Blumen' },
  { id: 'chorus_plant', name: 'Choruspflanze', category: 'Blumen' },
  
  // Farbstoffe
  { id: 'white_dye', name: 'Weißer Farbstoff', category: 'Farbstoffe' },
  { id: 'orange_dye', name: 'Oranger Farbstoff', category: 'Farbstoffe' },
  { id: 'magenta_dye', name: 'Magenta Farbstoff', category: 'Farbstoffe' },
  { id: 'light_blue_dye', name: 'Hellblauer Farbstoff', category: 'Farbstoffe' },
  { id: 'yellow_dye', name: 'Gelber Farbstoff', category: 'Farbstoffe' },
  { id: 'lime_dye', name: 'Hellgrüner Farbstoff', category: 'Farbstoffe' },
  { id: 'pink_dye', name: 'Rosa Farbstoff', category: 'Farbstoffe' },
  { id: 'gray_dye', name: 'Grauer Farbstoff', category: 'Farbstoffe' },
  { id: 'light_gray_dye', name: 'Hellgrauer Farbstoff', category: 'Farbstoffe' },
  { id: 'cyan_dye', name: 'Türkiser Farbstoff', category: 'Farbstoffe' },
  { id: 'purple_dye', name: 'Violetter Farbstoff', category: 'Farbstoffe' },
  { id: 'blue_dye', name: 'Blauer Farbstoff', category: 'Farbstoffe' },
  { id: 'brown_dye', name: 'Brauner Farbstoff', category: 'Farbstoffe' },
  { id: 'green_dye', name: 'Grüner Farbstoff', category: 'Farbstoffe' },
  { id: 'red_dye', name: 'Roter Farbstoff', category: 'Farbstoffe' },
  { id: 'black_dye', name: 'Schwarzer Farbstoff', category: 'Farbstoffe' },
  { id: 'bone_meal', name: 'Knochenmehl', category: 'Farbstoffe' },
  { id: 'ink_sac', name: 'Tintenbeutel', category: 'Farbstoffe' },
  { id: 'glow_ink_sac', name: 'Leucht-Tintenbeutel', category: 'Farbstoffe' },
  
  // Dekoration
  { id: 'chest', name: 'Truhe', category: 'Dekoration' },
  { id: 'trapped_chest', name: 'Redstone-Truhe', category: 'Dekoration' },
  { id: 'ender_chest', name: 'Endertruhe', category: 'Dekoration' },
  { id: 'barrel', name: 'Fass', category: 'Dekoration' },
  { id: 'bookshelf', name: 'Bücherregal', category: 'Dekoration' },
  { id: 'lectern', name: 'Lesepult', category: 'Dekoration' },
  { id: 'item_frame', name: 'Rahmen', category: 'Dekoration' },
  { id: 'glow_item_frame', name: 'Leuchtrahmen', category: 'Dekoration' },
  { id: 'painting', name: 'Gemälde', category: 'Dekoration' },
  { id: 'armor_stand', name: 'Rüstungsständer', category: 'Dekoration' },
  { id: 'flower_pot', name: 'Blumentopf', category: 'Dekoration' },
  { id: 'composter', name: 'Komposter', category: 'Dekoration' },
  { id: 'note_block', name: 'Notenblock', category: 'Dekoration' },
  { id: 'jukebox', name: 'Plattenspieler', category: 'Dekoration' },
  { id: 'bell', name: 'Glocke', category: 'Dekoration' },
  { id: 'beacon', name: 'Leuchtfeuer', category: 'Dekoration' },
  { id: 'conduit', name: 'Aquisator', category: 'Dekoration' },
  { id: 'end_crystal', name: 'Endkristall', category: 'Dekoration' },
  { id: 'enchanting_table', name: 'Zaubertisch', category: 'Dekoration' },
  { id: 'anvil', name: 'Amboss', category: 'Dekoration' },
  { id: 'chipped_anvil', name: 'Angeschlagener Amboss', category: 'Dekoration' },
  { id: 'damaged_anvil', name: 'Beschädigter Amboss', category: 'Dekoration' },
  { id: 'grindstone', name: 'Schleifstein', category: 'Dekoration' },
  { id: 'smithing_table', name: 'Schmiedetisch', category: 'Dekoration' },
  { id: 'cartography_table', name: 'Kartentisch', category: 'Dekoration' },
  { id: 'fletching_table', name: 'Bogentisch', category: 'Dekoration' },
  { id: 'loom', name: 'Webstuhl', category: 'Dekoration' },
  { id: 'stonecutter', name: 'Steinsäge', category: 'Dekoration' },
  { id: 'brewing_stand', name: 'Braustand', category: 'Dekoration' },
  { id: 'cauldron', name: 'Kessel', category: 'Dekoration' },
  { id: 'skeleton_skull', name: 'Skelettschädel', category: 'Dekoration' },
  { id: 'wither_skeleton_skull', name: 'Witherskelettschädel', category: 'Dekoration' },
  { id: 'zombie_head', name: 'Zombiekopf', category: 'Dekoration' },
  { id: 'creeper_head', name: 'Creeperkopf', category: 'Dekoration' },
  { id: 'dragon_head', name: 'Drachenkopf', category: 'Dekoration' },
  { id: 'player_head', name: 'Spielerkopf', category: 'Dekoration' },
  { id: 'piglin_head', name: 'Piglinkopf', category: 'Dekoration' },
  
  // Kerzen
  { id: 'candle', name: 'Kerze', category: 'Kerzen' },
  { id: 'white_candle', name: 'Weiße Kerze', category: 'Kerzen' },
  { id: 'orange_candle', name: 'Orange Kerze', category: 'Kerzen' },
  { id: 'magenta_candle', name: 'Magenta Kerze', category: 'Kerzen' },
  { id: 'light_blue_candle', name: 'Hellblaue Kerze', category: 'Kerzen' },
  { id: 'yellow_candle', name: 'Gelbe Kerze', category: 'Kerzen' },
  { id: 'lime_candle', name: 'Hellgrüne Kerze', category: 'Kerzen' },
  { id: 'pink_candle', name: 'Rosa Kerze', category: 'Kerzen' },
  { id: 'gray_candle', name: 'Graue Kerze', category: 'Kerzen' },
  { id: 'light_gray_candle', name: 'Hellgraue Kerze', category: 'Kerzen' },
  { id: 'cyan_candle', name: 'Türkise Kerze', category: 'Kerzen' },
  { id: 'purple_candle', name: 'Violette Kerze', category: 'Kerzen' },
  { id: 'blue_candle', name: 'Blaue Kerze', category: 'Kerzen' },
  { id: 'brown_candle', name: 'Braune Kerze', category: 'Kerzen' },
  { id: 'green_candle', name: 'Grüne Kerze', category: 'Kerzen' },
  { id: 'red_candle', name: 'Rote Kerze', category: 'Kerzen' },
  { id: 'black_candle', name: 'Schwarze Kerze', category: 'Kerzen' },
  
  // Glas
  { id: 'glass', name: 'Glas', category: 'Glas' },
  { id: 'white_stained_glass', name: 'Weißes Glas', category: 'Glas' },
  { id: 'orange_stained_glass', name: 'Oranges Glas', category: 'Glas' },
  { id: 'magenta_stained_glass', name: 'Magenta Glas', category: 'Glas' },
  { id: 'light_blue_stained_glass', name: 'Hellblaues Glas', category: 'Glas' },
  { id: 'yellow_stained_glass', name: 'Gelbes Glas', category: 'Glas' },
  { id: 'lime_stained_glass', name: 'Hellgrünes Glas', category: 'Glas' },
  { id: 'pink_stained_glass', name: 'Rosa Glas', category: 'Glas' },
  { id: 'gray_stained_glass', name: 'Graues Glas', category: 'Glas' },
  { id: 'light_gray_stained_glass', name: 'Hellgraues Glas', category: 'Glas' },
  { id: 'cyan_stained_glass', name: 'Türkises Glas', category: 'Glas' },
  { id: 'purple_stained_glass', name: 'Violettes Glas', category: 'Glas' },
  { id: 'blue_stained_glass', name: 'Blaues Glas', category: 'Glas' },
  { id: 'brown_stained_glass', name: 'Braunes Glas', category: 'Glas' },
  { id: 'green_stained_glass', name: 'Grünes Glas', category: 'Glas' },
  { id: 'red_stained_glass', name: 'Rotes Glas', category: 'Glas' },
  { id: 'black_stained_glass', name: 'Schwarzes Glas', category: 'Glas' },
  { id: 'tinted_glass', name: 'Getöntes Glas', category: 'Glas' },
  { id: 'glass_pane', name: 'Glasscheibe', category: 'Glas' },
  
  // Beton
  { id: 'white_concrete', name: 'Weißer Beton', category: 'Beton' },
  { id: 'orange_concrete', name: 'Oranger Beton', category: 'Beton' },
  { id: 'magenta_concrete', name: 'Magenta Beton', category: 'Beton' },
  { id: 'light_blue_concrete', name: 'Hellblauer Beton', category: 'Beton' },
  { id: 'yellow_concrete', name: 'Gelber Beton', category: 'Beton' },
  { id: 'lime_concrete', name: 'Hellgrüner Beton', category: 'Beton' },
  { id: 'pink_concrete', name: 'Rosa Beton', category: 'Beton' },
  { id: 'gray_concrete', name: 'Grauer Beton', category: 'Beton' },
  { id: 'light_gray_concrete', name: 'Hellgrauer Beton', category: 'Beton' },
  { id: 'cyan_concrete', name: 'Türkiser Beton', category: 'Beton' },
  { id: 'purple_concrete', name: 'Violetter Beton', category: 'Beton' },
  { id: 'blue_concrete', name: 'Blauer Beton', category: 'Beton' },
  { id: 'brown_concrete', name: 'Brauner Beton', category: 'Beton' },
  { id: 'green_concrete', name: 'Grüner Beton', category: 'Beton' },
  { id: 'red_concrete', name: 'Roter Beton', category: 'Beton' },
  { id: 'black_concrete', name: 'Schwarzer Beton', category: 'Beton' },
  { id: 'white_concrete_powder', name: 'Weißer Trockenbeton', category: 'Beton' },
  { id: 'orange_concrete_powder', name: 'Oranger Trockenbeton', category: 'Beton' },
  { id: 'magenta_concrete_powder', name: 'Magenta Trockenbeton', category: 'Beton' },
  { id: 'light_blue_concrete_powder', name: 'Hellblauer Trockenbeton', category: 'Beton' },
  { id: 'yellow_concrete_powder', name: 'Gelber Trockenbeton', category: 'Beton' },
  { id: 'lime_concrete_powder', name: 'Hellgrüner Trockenbeton', category: 'Beton' },
  { id: 'pink_concrete_powder', name: 'Rosa Trockenbeton', category: 'Beton' },
  { id: 'gray_concrete_powder', name: 'Grauer Trockenbeton', category: 'Beton' },
  { id: 'light_gray_concrete_powder', name: 'Hellgrauer Trockenbeton', category: 'Beton' },
  { id: 'cyan_concrete_powder', name: 'Türkiser Trockenbeton', category: 'Beton' },
  { id: 'purple_concrete_powder', name: 'Violetter Trockenbeton', category: 'Beton' },
  { id: 'blue_concrete_powder', name: 'Blauer Trockenbeton', category: 'Beton' },
  { id: 'brown_concrete_powder', name: 'Brauner Trockenbeton', category: 'Beton' },
  { id: 'green_concrete_powder', name: 'Grüner Trockenbeton', category: 'Beton' },
  { id: 'red_concrete_powder', name: 'Roter Trockenbeton', category: 'Beton' },
  { id: 'black_concrete_powder', name: 'Schwarzer Trockenbeton', category: 'Beton' },
  
  // Wolle
  { id: 'white_wool', name: 'Weiße Wolle', category: 'Wolle' },
  { id: 'orange_wool', name: 'Orange Wolle', category: 'Wolle' },
  { id: 'magenta_wool', name: 'Magenta Wolle', category: 'Wolle' },
  { id: 'light_blue_wool', name: 'Hellblaue Wolle', category: 'Wolle' },
  { id: 'yellow_wool', name: 'Gelbe Wolle', category: 'Wolle' },
  { id: 'lime_wool', name: 'Hellgrüne Wolle', category: 'Wolle' },
  { id: 'pink_wool', name: 'Rosa Wolle', category: 'Wolle' },
  { id: 'gray_wool', name: 'Graue Wolle', category: 'Wolle' },
  { id: 'light_gray_wool', name: 'Hellgraue Wolle', category: 'Wolle' },
  { id: 'cyan_wool', name: 'Türkise Wolle', category: 'Wolle' },
  { id: 'purple_wool', name: 'Violette Wolle', category: 'Wolle' },
  { id: 'blue_wool', name: 'Blaue Wolle', category: 'Wolle' },
  { id: 'brown_wool', name: 'Braune Wolle', category: 'Wolle' },
  { id: 'green_wool', name: 'Grüne Wolle', category: 'Wolle' },
  { id: 'red_wool', name: 'Rote Wolle', category: 'Wolle' },
  { id: 'black_wool', name: 'Schwarze Wolle', category: 'Wolle' },
  { id: 'carpet', name: 'Teppich', category: 'Wolle' },
  
  // Terrakotta
  { id: 'terracotta', name: 'Terrakotta', category: 'Terrakotta' },
  { id: 'white_terracotta', name: 'Weiße Terrakotta', category: 'Terrakotta' },
  { id: 'orange_terracotta', name: 'Orange Terrakotta', category: 'Terrakotta' },
  { id: 'magenta_terracotta', name: 'Magenta Terrakotta', category: 'Terrakotta' },
  { id: 'light_blue_terracotta', name: 'Hellblaue Terrakotta', category: 'Terrakotta' },
  { id: 'yellow_terracotta', name: 'Gelbe Terrakotta', category: 'Terrakotta' },
  { id: 'lime_terracotta', name: 'Hellgrüne Terrakotta', category: 'Terrakotta' },
  { id: 'pink_terracotta', name: 'Rosa Terrakotta', category: 'Terrakotta' },
  { id: 'gray_terracotta', name: 'Graue Terrakotta', category: 'Terrakotta' },
  { id: 'light_gray_terracotta', name: 'Hellgraue Terrakotta', category: 'Terrakotta' },
  { id: 'cyan_terracotta', name: 'Türkise Terrakotta', category: 'Terrakotta' },
  { id: 'purple_terracotta', name: 'Violette Terrakotta', category: 'Terrakotta' },
  { id: 'blue_terracotta', name: 'Blaue Terrakotta', category: 'Terrakotta' },
  { id: 'brown_terracotta', name: 'Braune Terrakotta', category: 'Terrakotta' },
  { id: 'green_terracotta', name: 'Grüne Terrakotta', category: 'Terrakotta' },
  { id: 'red_terracotta', name: 'Rote Terrakotta', category: 'Terrakotta' },
  { id: 'black_terracotta', name: 'Schwarze Terrakotta', category: 'Terrakotta' },
  { id: 'glazed_terracotta', name: 'Glasierte Terrakotta', category: 'Terrakotta' },
  
  // Redstone
  { id: 'redstone', name: 'Redstone', category: 'Redstone' },
  { id: 'redstone_torch', name: 'Redstone-Fackel', category: 'Redstone' },
  { id: 'redstone_repeater', name: 'Redstone-Verstärker', category: 'Redstone' },
  { id: 'redstone_comparator', name: 'Redstone-Komparator', category: 'Redstone' },
  { id: 'piston', name: 'Kolben', category: 'Redstone' },
  { id: 'sticky_piston', name: 'Klebriger Kolben', category: 'Redstone' },
  { id: 'slime_block', name: 'Schleimblock', category: 'Redstone' },
  { id: 'honey_block', name: 'Honigblock', category: 'Redstone' },
  { id: 'observer', name: 'Beobachter', category: 'Redstone' },
  { id: 'hopper', name: 'Trichter', category: 'Redstone' },
  { id: 'dispenser', name: 'Werfer', category: 'Redstone' },
  { id: 'dropper', name: 'Spender', category: 'Redstone' },
  { id: 'target', name: 'Zielblock', category: 'Redstone' },
  { id: 'lever', name: 'Hebel', category: 'Redstone' },
  { id: 'stone_button', name: 'Steinknopf', category: 'Redstone' },
  { id: 'oak_button', name: 'Eichenholzknopf', category: 'Redstone' },
  { id: 'tripwire_hook', name: 'Haken', category: 'Redstone' },
  { id: 'daylight_detector', name: 'Tageslichtsensor', category: 'Redstone' },
  { id: 'lightning_rod', name: 'Blitzableiter', category: 'Redstone' },
  { id: 'sculk_vein', name: 'Sculk-Ader', category: 'Redstone' },
  
  // Transport
  { id: 'rail', name: 'Schiene', category: 'Transport' },
  { id: 'powered_rail', name: 'Antriebsschiene', category: 'Transport' },
  { id: 'detector_rail', name: 'Sensorschiene', category: 'Transport' },
  { id: 'activator_rail', name: 'Aktivierungsschiene', category: 'Transport' },
  { id: 'minecart', name: 'Lore', category: 'Transport' },
  { id: 'chest_minecart', name: 'Güterlore', category: 'Transport' },
  { id: 'furnace_minecart', name: 'Antriebslore', category: 'Transport' },
  { id: 'tnt_minecart', name: 'TNT-Lore', category: 'Transport' },
  { id: 'hopper_minecart', name: 'Trichterlore', category: 'Transport' },
  { id: 'carrot_on_a_stick', name: 'Karottenrute', category: 'Transport' },
  { id: 'warped_fungus_on_a_stick', name: 'Wirrpilzrute', category: 'Transport' },
  { id: 'saddle', name: 'Sattel', category: 'Transport' },
  { id: 'oak_boat', name: 'Eichenholzboot', category: 'Transport' },
  { id: 'chest_boat', name: 'Boot mit Truhe', category: 'Transport' },
  
  // Nahrung
  { id: 'apple', name: 'Apfel', category: 'Nahrung' },
  { id: 'golden_apple', name: 'Goldener Apfel', category: 'Nahrung' },
  { id: 'enchanted_golden_apple', name: 'Verzauberter goldener Apfel', category: 'Nahrung' },
  { id: 'bread', name: 'Brot', category: 'Nahrung' },
  { id: 'porkchop', name: 'Rohes Schweinefleisch', category: 'Nahrung' },
  { id: 'cooked_porkchop', name: 'Gebratenes Schweinefleisch', category: 'Nahrung' },
  { id: 'beef', name: 'Rohes Rindfleisch', category: 'Nahrung' },
  { id: 'cooked_beef', name: 'Steak', category: 'Nahrung' },
  { id: 'chicken', name: 'Rohes Hühnchen', category: 'Nahrung' },
  { id: 'cooked_chicken', name: 'Gebratenes Hühnchen', category: 'Nahrung' },
  { id: 'mutton', name: 'Rohes Hammelfleisch', category: 'Nahrung' },
  { id: 'cooked_mutton', name: 'Gebratenes Hammelfleisch', category: 'Nahrung' },
  { id: 'rabbit', name: 'Rohes Kaninchen', category: 'Nahrung' },
  { id: 'cooked_rabbit', name: 'Gebratenes Kaninchen', category: 'Nahrung' },
  { id: 'cod', name: 'Roher Kabeljau', category: 'Nahrung' },
  { id: 'cooked_cod', name: 'Gebratener Kabeljau', category: 'Nahrung' },
  { id: 'salmon', name: 'Roher Lachs', category: 'Nahrung' },
  { id: 'cooked_salmon', name: 'Gebratener Lachs', category: 'Nahrung' },
  { id: 'tropical_fish', name: 'Tropenfisch', category: 'Nahrung' },
  { id: 'pufferfish', name: 'Kugelfisch', category: 'Nahrung' },
  { id: 'cookie', name: 'Keks', category: 'Nahrung' },
  { id: 'cake', name: 'Kuchen', category: 'Nahrung' },
  { id: 'pumpkin_pie', name: 'Kürbiskuchen', category: 'Nahrung' },
  { id: 'mushroom_stew', name: 'Pilzsuppe', category: 'Nahrung' },
  { id: 'rabbit_stew', name: 'Kaninchenragout', category: 'Nahrung' },
  { id: 'beetroot_soup', name: 'Rote-Bete-Suppe', category: 'Nahrung' },
  { id: 'honey_bottle', name: 'Honigflasche', category: 'Nahrung' },
  { id: 'rotten_flesh', name: 'Verrottetes Fleisch', category: 'Nahrung' },
  { id: 'spider_eye', name: 'Spinnenauge', category: 'Nahrung' },
  { id: 'poisonous_potato', name: 'Giftige Kartoffel', category: 'Nahrung' },
  
  // Werkzeuge
  { id: 'wooden_pickaxe', name: 'Holzspitzhacke', category: 'Werkzeuge' },
  { id: 'stone_pickaxe', name: 'Steinspitzhacke', category: 'Werkzeuge' },
  { id: 'iron_pickaxe', name: 'Eisenspitzhacke', category: 'Werkzeuge' },
  { id: 'golden_pickaxe', name: 'Goldspitzhacke', category: 'Werkzeuge' },
  { id: 'diamond_pickaxe', name: 'Diamantspitzhacke', category: 'Werkzeuge' },
  { id: 'netherite_pickaxe', name: 'Netheritspitzhacke', category: 'Werkzeuge' },
  { id: 'wooden_axe', name: 'Holzaxt', category: 'Werkzeuge' },
  { id: 'stone_axe', name: 'Steinaxt', category: 'Werkzeuge' },
  { id: 'iron_axe', name: 'Eisenaxt', category: 'Werkzeuge' },
  { id: 'golden_axe', name: 'Goldaxt', category: 'Werkzeuge' },
  { id: 'diamond_axe', name: 'Diamantaxt', category: 'Werkzeuge' },
  { id: 'netherite_axe', name: 'Netheritaxt', category: 'Werkzeuge' },
  { id: 'wooden_shovel', name: 'Holzschaufel', category: 'Werkzeuge' },
  { id: 'stone_shovel', name: 'Steinschaufel', category: 'Werkzeuge' },
  { id: 'iron_shovel', name: 'Eisenschaufel', category: 'Werkzeuge' },
  { id: 'golden_shovel', name: 'Goldschaufel', category: 'Werkzeuge' },
  { id: 'diamond_shovel', name: 'Diamantschaufel', category: 'Werkzeuge' },
  { id: 'netherite_shovel', name: 'Netheritschaufel', category: 'Werkzeuge' },
  { id: 'wooden_hoe', name: 'Holzhacke', category: 'Werkzeuge' },
  { id: 'stone_hoe', name: 'Steinhacke', category: 'Werkzeuge' },
  { id: 'iron_hoe', name: 'Eisenhacke', category: 'Werkzeuge' },
  { id: 'golden_hoe', name: 'Goldhacke', category: 'Werkzeuge' },
  { id: 'diamond_hoe', name: 'Diamanthacke', category: 'Werkzeuge' },
  { id: 'netherite_hoe', name: 'Netherithacke', category: 'Werkzeuge' },
  { id: 'shears', name: 'Schere', category: 'Werkzeuge' },
  { id: 'flint_and_steel', name: 'Feuerzeug', category: 'Werkzeuge' },
  { id: 'brush', name: 'Pinsel', category: 'Werkzeuge' },
  { id: 'fishing_rod', name: 'Angel', category: 'Werkzeuge' },
  { id: 'lead', name: 'Leine', category: 'Werkzeuge' },
  { id: 'name_tag', name: 'Namensschild', category: 'Werkzeuge' },
  { id: 'compass', name: 'Kompass', category: 'Werkzeuge' },
  { id: 'recovery_compass', name: 'Wiederherstellungskompass', category: 'Werkzeuge' },
  { id: 'clock', name: 'Uhr', category: 'Werkzeuge' },
  { id: 'spyglass', name: 'Fernglas', category: 'Werkzeuge' },
  { id: 'map', name: 'Karte', category: 'Werkzeuge' },
  { id: 'bucket', name: 'Eimer', category: 'Werkzeuge' },
  { id: 'water_bucket', name: 'Wassereimer', category: 'Werkzeuge' },
  { id: 'lava_bucket', name: 'Lavaeimer', category: 'Werkzeuge' },
  { id: 'powder_snow_bucket', name: 'Pulverschneeeimer', category: 'Werkzeuge' },
  { id: 'milk_bucket', name: 'Milcheimer', category: 'Werkzeuge' },
  { id: 'pufferfish_bucket', name: 'Kugelfischeimer', category: 'Werkzeuge' },
  { id: 'salmon_bucket', name: 'Lachseimer', category: 'Werkzeuge' },
  { id: 'cod_bucket', name: 'Kabeljaueimer', category: 'Werkzeuge' },
  { id: 'tropical_fish_bucket', name: 'Tropenfischeimer', category: 'Werkzeuge' },
  { id: 'axolotl_bucket', name: 'Axolotleimer', category: 'Werkzeuge' },
  { id: 'tadpole_bucket', name: 'Kaulquappeneimer', category: 'Werkzeuge' },
  
  // Waffen & Rüstung
  { id: 'wooden_sword', name: 'Holzschwert', category: 'Waffen' },
  { id: 'stone_sword', name: 'Steinschwert', category: 'Waffen' },
  { id: 'iron_sword', name: 'Eisenschwert', category: 'Waffen' },
  { id: 'golden_sword', name: 'Goldschwert', category: 'Waffen' },
  { id: 'diamond_sword', name: 'Diamantschwert', category: 'Waffen' },
  { id: 'netherite_sword', name: 'Netherritschwert', category: 'Waffen' },
  { id: 'bow', name: 'Bogen', category: 'Waffen' },
  { id: 'crossbow', name: 'Armbrust', category: 'Waffen' },
  { id: 'arrow', name: 'Pfeil', category: 'Waffen' },
  { id: 'spectral_arrow', name: 'Spektralpfeil', category: 'Waffen' },
  { id: 'trident', name: 'Dreizack', category: 'Waffen' },
  { id: 'shield', name: 'Schild', category: 'Waffen' },
  { id: 'totem_of_undying', name: 'Totem der Unsterblichkeit', category: 'Waffen' },
  { id: 'turtle_helmet', name: 'Schildkrötenpanzer', category: 'Waffen' },
  { id: 'leather_helmet', name: 'Lederkappe', category: 'Waffen' },
  { id: 'leather_chestplate', name: 'Lederjacke', category: 'Waffen' },
  { id: 'leather_leggings', name: 'Lederhose', category: 'Waffen' },
  { id: 'leather_boots', name: 'Lederstiefel', category: 'Waffen' },
  { id: 'chainmail_helmet', name: 'Kettenhaube', category: 'Waffen' },
  { id: 'chainmail_chestplate', name: 'Kettenhemd', category: 'Waffen' },
  { id: 'chainmail_leggings', name: 'Kettenhose', category: 'Waffen' },
  { id: 'chainmail_boots', name: 'Kettenstiefel', category: 'Waffen' },
  { id: 'iron_helmet', name: 'Eisenhelm', category: 'Waffen' },
  { id: 'iron_chestplate', name: 'Eisenharnisch', category: 'Waffen' },
  { id: 'iron_leggings', name: 'Eisenbeinschutz', category: 'Waffen' },
  { id: 'iron_boots', name: 'Eisenstiefel', category: 'Waffen' },
  { id: 'golden_helmet', name: 'Goldhelm', category: 'Waffen' },
  { id: 'golden_chestplate', name: 'Goldharnisch', category: 'Waffen' },
  { id: 'golden_leggings', name: 'Goldbeinschutz', category: 'Waffen' },
  { id: 'golden_boots', name: 'Goldstiefel', category: 'Waffen' },
  { id: 'diamond_helmet', name: 'Diamanthelm', category: 'Waffen' },
  { id: 'diamond_chestplate', name: 'Diamantharnisch', category: 'Waffen' },
  { id: 'diamond_leggings', name: 'Diamantbeinschutz', category: 'Waffen' },
  { id: 'diamond_boots', name: 'Diamantstiefel', category: 'Waffen' },
  { id: 'netherite_helmet', name: 'Netherithelm', category: 'Waffen' },
  { id: 'netherite_chestplate', name: 'Netheritharnisch', category: 'Waffen' },
  { id: 'netherite_leggings', name: 'Netheritebeinschutz', category: 'Waffen' },
  { id: 'netherite_boots', name: 'Netheritstiefel', category: 'Waffen' },
  
  // Sonstiges
  { id: 'stick', name: 'Stock', category: 'Sonstiges' },
  { id: 'bowl', name: 'Schüssel', category: 'Sonstiges' },
  { id: 'string', name: 'Faden', category: 'Sonstiges' },
  { id: 'feather', name: 'Feder', category: 'Sonstiges' },
  { id: 'gunpowder', name: 'Schwarzpulver', category: 'Sonstiges' },
  { id: 'wheat_seeds', name: 'Weizensamen', category: 'Sonstiges' },
  { id: 'flint', name: 'Feuerstein', category: 'Sonstiges' },
  { id: 'bucket', name: 'Eimer', category: 'Sonstiges' },
  { id: 'snowball', name: 'Schneeball', category: 'Sonstiges' },
  { id: 'leather', name: 'Leder', category: 'Sonstiges' },
  { id: 'brick', name: 'Ziegel', category: 'Sonstiges' },
  { id: 'clay_ball', name: 'Tonklumpen', category: 'Sonstiges' },
  { id: 'paper', name: 'Papier', category: 'Sonstiges' },
  { id: 'book', name: 'Buch', category: 'Sonstiges' },
  { id: 'slime_ball', name: 'Schleimball', category: 'Sonstiges' },
  { id: 'egg', name: 'Ei', category: 'Sonstiges' },
  { id: 'bone', name: 'Knochen', category: 'Sonstiges' },
  { id: 'ender_pearl', name: 'Enderperle', category: 'Sonstiges' },
  { id: 'blaze_rod', name: 'Lohenrute', category: 'Sonstiges' },
  { id: 'gold_nugget', name: 'Goldklumpen', category: 'Sonstiges' },
  { id: 'iron_nugget', name: 'Eisenklumpen', category: 'Sonstiges' },
  { id: 'nether_wart', name: 'Netherwarze', category: 'Sonstiges' },
  { id: 'ender_eye', name: 'Enderauge', category: 'Sonstiges' },
  { id: 'spawn_egg', name: 'Spawn-Ei', category: 'Sonstiges' },
  { id: 'bottle_o_enchanting', name: 'Erfahrungsfläschchen', category: 'Sonstiges' },
  { id: 'fire_charge', name: 'Feuerkugel', category: 'Sonstiges' },
  { id: 'writable_book', name: 'Buch und Feder', category: 'Sonstiges' },
  { id: 'emerald', name: 'Smaragd', category: 'Sonstiges' },
  { id: 'item_frame', name: 'Rahmen', category: 'Sonstiges' },
  { id: 'flower_pot', name: 'Blumentopf', category: 'Sonstiges' },
  { id: 'skull', name: 'Schädel', category: 'Sonstiges' },
  { id: 'firework_star', name: 'Feuerwerksstern', category: 'Sonstiges' },
  { id: 'nether_star', name: 'Netherstern', category: 'Sonstiges' },
  { id: 'pumpkin_seeds', name: 'Kürbiskerne', category: 'Sonstiges' },
  { id: 'melon_seeds', name: 'Melonenkerne', category: 'Sonstiges' },
  { id: 'firework_rocket', name: 'Feuerwerksrakete', category: 'Sonstiges' },
  { id: 'nether_brick', name: 'Netherziegel', category: 'Sonstiges' },
  { id: 'prismarine_shard', name: 'Prismarinscherbe', category: 'Sonstiges' },
  { id: 'prismarine_crystals', name: 'Prismarinkristalle', category: 'Sonstiges' },
  { id: 'rabbit_hide', name: 'Kaninchenfell', category: 'Sonstiges' },
  { id: 'armor_stand', name: 'Rüstungsständer', category: 'Sonstiges' },
  { id: 'iron_horse_armor', name: 'Eisenpferderüstung', category: 'Sonstiges' },
  { id: 'golden_horse_armor', name: 'Goldpferderüstung', category: 'Sonstiges' },
  { id: 'diamond_horse_armor', name: 'Diamantpferderüstung', category: 'Sonstiges' },
  { id: 'leather_horse_armor', name: 'Lederpferderüstung', category: 'Sonstiges' },
  { id: 'chorus_fruit', name: 'Chorusfrucht', category: 'Sonstiges' },
  { id: 'popped_chorus_fruit', name: 'Geplatzte Chorusfrucht', category: 'Sonstiges' },
  { id: 'beetroot_seeds', name: 'Rote-Bete-Samen', category: 'Sonstiges' },
  { id: 'shulker_shell', name: 'Shulkerschale', category: 'Sonstiges' },
  { id: 'iron_ingot', name: 'Eisenbarren', category: 'Sonstiges' },
  { id: 'gold_ingot', name: 'Goldbarren', category: 'Sonstiges' },
  { id: 'copper_ingot', name: 'Kupferbarren', category: 'Sonstiges' },
  { id: 'netherite_scrap', name: 'Netheritschrott', category: 'Sonstiges' },
  { id: 'netherite_ingot', name: 'Netheritbarren', category: 'Sonstiges' },
  { id: 'phantom_membrane', name: 'Phantomhaut', category: 'Sonstiges' },
  { id: 'nautilus_shell', name: 'Nautilusschale', category: 'Sonstiges' },
  { id: 'heart_of_the_sea', name: 'Herz des Meeres', category: 'Sonstiges' },
  { id: 'crossbow', name: 'Armbrust', category: 'Sonstiges' },
  { id: 'suspicious_stew', name: 'Seltsame Suppe', category: 'Sonstiges' },
  { id: 'flower_banner_pattern', name: 'Bannervorlage', category: 'Sonstiges' },
  { id: 'creeper_banner_pattern', name: 'Creeper-Bannervorlage', category: 'Sonstiges' },
  { id: 'skull_banner_pattern', name: 'Schädel-Bannervorlage', category: 'Sonstiges' },
  { id: 'mojang_banner_pattern', name: 'Mojang-Bannervorlage', category: 'Sonstiges' },
  { id: 'globe_banner_pattern', name: 'Globus-Bannervorlage', category: 'Sonstiges' },
  { id: 'piglin_banner_pattern', name: 'Piglin-Bannervorlage', category: 'Sonstiges' },
  { id: 'goat_horn', name: 'Ziegenhorn', category: 'Sonstiges' },
  { id: 'music_disc_13', name: 'Schallplatte', category: 'Sonstiges' },
  { id: 'disc_fragment_5', name: 'Schallplattenfragment', category: 'Sonstiges' },
  { id: 'echo_shard', name: 'Echoscherbe', category: 'Sonstiges' },
  { id: 'brush', name: 'Pinsel', category: 'Sonstiges' },
  { id: 'pottery_sherd', name: 'Tonscherbe', category: 'Sonstiges' },
  { id: 'snort_pottery_sherd', name: 'Schnaub-Tonscherbe', category: 'Sonstiges' },
  { id: 'archer_pottery_sherd', name: 'Schützen-Tonscherbe', category: 'Sonstiges' },
  { id: 'prize_pottery_sherd', name: 'Preis-Tonscherbe', category: 'Sonstiges' },
  { id: 'skull_pottery_sherd', name: 'Schädel-Tonscherbe', category: 'Sonstiges' },
  { id: 'arms_up_pottery_sherd', name: 'Arme-hoch-Tonscherbe', category: 'Sonstiges' },
  { id: 'brewer_pottery_sherd', name: 'Brauer-Tonscherbe', category: 'Sonstiges' },
  { id: 'blade_pottery_sherd', name: 'Klingen-Tonscherbe', category: 'Sonstiges' },
  { id: 'explorer_pottery_sherd', name: 'Forscher-Tonscherbe', category: 'Sonstiges' },
  { id: 'heart_pottery_sherd', name: 'Herz-Tonscherbe', category: 'Sonstiges' },
  { id: 'heartbreak_pottery_sherd', name: 'Herzschmerz-Tonscherbe', category: 'Sonstiges' },
  { id: 'howl_pottery_sherd', name: 'Heul-Tonscherbe', category: 'Sonstiges' },
  { id: 'miner_pottery_sherd', name: 'Bergbau-Tonscherbe', category: 'Sonstiges' },
  { id: 'mourner_pottery_sherd', name: 'Trauer-Tonscherbe', category: 'Sonstiges' },
  { id: 'plenty_pottery_sherd', name: 'Fülle-Tonscherbe', category: 'Sonstiges' },
  { id: 'sheaf_pottery_sherd', name: 'Garben-Tonscherbe', category: 'Sonstiges' },
  { id: 'shelter_pottery_sherd', name: 'Schutz-Tonscherbe', category: 'Sonstiges' },
  { id: 'snort_pottery_sherd', name: 'Schnaub-Tonscherbe', category: 'Sonstiges' },
  { id: 'angler_pottery_sherd', name: 'Angler-Tonscherbe', category: 'Sonstiges' },
  { id: 'danger_pottery_sherd', name: 'Gefahren-Tonscherbe', category: 'Sonstiges' },
  { id: 'friend_pottery_sherd', name: 'Freundschafts-Tonscherbe', category: 'Sonstiges' },
  { id: 'burn_pottery_sherd', name: 'Brenn-Tonscherbe', category: 'Sonstiges' },
  { id: 'flow_pottery_sherd', name: 'Fluss-Tonscherbe', category: 'Sonstiges' },
  { id: 'guster_pottery_sherd', name: 'Bö-Tonscherbe', category: 'Sonstiges' },
  { id: 'scrape_pottery_sherd', name: 'Kratz-Tonscherbe', category: 'Sonstiges' },
  { id: 'netherite_upgrade_smithing_template', name: 'Schmiedevorlage', category: 'Sonstiges' },
  { id: 'sentry_armor_trim_smithing_template', name: 'Wächter-Rüstungsbesatz', category: 'Sonstiges' },
  { id: 'vex_armor_trim_smithing_template', name: 'Plagegeist-Rüstungsbesatz', category: 'Sonstiges' },
  { id: 'wild_armor_trim_smithing_template', name: 'Wildnis-Rüstungsbesatz', category: 'Sonstiges' },
  { id: 'coast_armor_trim_smithing_template', name: 'Küsten-Rüstungsbesatz', category: 'Sonstiges' },
  { id: 'dune_armor_trim_smithing_template', name: 'Dünen-Rüstungsbesatz', category: 'Sonstiges' },
  { id: 'wayfinder_armor_trim_smithing_template', name: 'Wegweiser-Rüstungsbesatz', category: 'Sonstiges' },
  { id: 'raiser_armor_trim_smithing_template', name: 'Erheber-Rüstungsbesatz', category: 'Sonstiges' },
  { id: 'shaper_armor_trim_smithing_template', name: 'Former-Rüstungsbesatz', category: 'Sonstiges' },
  { id: 'host_armor_trim_smithing_template', name: 'Gastgeber-Rüstungsbesatz', category: 'Sonstiges' },
  { id: 'ward_armor_trim_smithing_template', name: 'Wärter-Rüstungsbesatz', category: 'Sonstiges' },
  { id: 'silence_armor_trim_smithing_template', name: 'Stille-Rüstungsbesatz', category: 'Sonstiges' },
  { id: 'tide_armor_trim_smithing_template', name: 'Gezeiten-Rüstungsbesatz', category: 'Sonstiges' },
  { id: 'snout_armor_trim_smithing_template', name: 'Schnauzen-Rüstungsbesatz', category: 'Sonstiges' },
  { id: 'rib_armor_trim_smithing_template', name: 'Rippen-Rüstungsbesatz', category: 'Sonstiges' },
  { id: 'eye_armor_trim_smithing_template', name: 'Augen-Rüstungsbesatz', category: 'Sonstiges' },
  { id: 'spire_armor_trim_smithing_template', name: 'Turmspitzen-Rüstungsbesatz', category: 'Sonstiges' },
  { id: 'bolt_armor_trim_smithing_template', name: 'Bolzen-Rüstungsbesatz', category: 'Sonstiges' },
  { id: 'flow_armor_trim_smithing_template', name: 'Fluss-Rüstungsbesatz', category: 'Sonstiges' },
  { id: 'ominous_trial_key', name: 'Ominöser Trial-Schlüssel', category: 'Sonstiges' },
  { id: 'trial_key', name: 'Trial-Schlüssel', category: 'Sonstiges' },
  { id: 'wind_charge', name: 'Windladung', category: 'Sonstiges' },
  { id: 'breeze_rod', name: 'Breeze-Rute', category: 'Sonstiges' },
  { id: 'heavy_core', name: 'Schwerer Kern', category: 'Sonstiges' },
  { id: 'mace', name: 'Streitkolben', category: 'Sonstiges' },
  { id: 'wolf_armor', name: 'Wolfsrüstung', category: 'Sonstiges' },
  { id: 'armadillo_scute', name: 'Gürteltierhorn', category: 'Sonstiges' },
  { id: 'wolf_spawn_egg', name: 'Wolf-Spawn-Ei', category: 'Sonstiges' },
  { id: 'armadillo_spawn_egg', name: 'Gürteltier-Spawn-Ei', category: 'Sonstiges' },
  { id: 'bogged_spawn_egg', name: 'Sumpfskelett-Spawn-Ei', category: 'Sonstiges' },
  { id: 'breeze_spawn_egg', name: 'Breeze-Spawn-Ei', category: 'Sonstiges' },
  { id: 'bundle', name: 'Bündel', category: 'Sonstiges' },
  { id: 'white_bundle', name: 'Weißes Bündel', category: 'Sonstiges' },
  { id: 'orange_bundle', name: 'Oranges Bündel', category: 'Sonstiges' },
  { id: 'magenta_bundle', name: 'Magenta Bündel', category: 'Sonstiges' },
  { id: 'light_blue_bundle', name: 'Hellblaues Bündel', category: 'Sonstiges' },
  { id: 'yellow_bundle', name: 'Gelbes Bündel', category: 'Sonstiges' },
  { id: 'lime_bundle', name: 'Hellgrünes Bündel', category: 'Sonstiges' },
  { id: 'pink_bundle', name: 'Rosa Bündel', category: 'Sonstiges' },
  { id: 'gray_bundle', name: 'Graues Bündel', category: 'Sonstiges' },
  { id: 'light_gray_bundle', name: 'Hellgraues Bündel', category: 'Sonstiges' },
  { id: 'cyan_bundle', name: 'Türkises Bündel', category: 'Sonstiges' },
  { id: 'purple_bundle', name: 'Violettes Bündel', category: 'Sonstiges' },
  { id: 'blue_bundle', name: 'Blaues Bündel', category: 'Sonstiges' },
  { id: 'brown_bundle', name: 'Braunes Bündel', category: 'Sonstiges' },
  { id: 'green_bundle', name: 'Grünes Bündel', category: 'Sonstiges' },
  { id: 'red_bundle', name: 'Rotes Bündel', category: 'Sonstiges' },
  { id: 'black_bundle', name: 'Schwarzes Bündel', category: 'Sonstiges' },
  { id: 'resin_clump', name: 'Harzklumpen', category: 'Sonstiges' },
  { id: 'resin_brick', name: 'Harzziegel', category: 'Sonstiges' },
  { id: 'creaking_spawn_egg', name: 'Creaking-Spawn-Ei', category: 'Sonstiges' },
  { id: 'pale_oak_sapling', name: 'Bleicheichensetzling', category: 'Sonstiges' },
  { id: 'pale_oak_leaves', name: 'Bleicheichenlaub', category: 'Sonstiges' },
  { id: 'pale_oak_log', name: 'Bleicheichenstamm', category: 'Sonstiges' },
  { id: 'pale_oak_planks', name: 'Bleicheichenbretter', category: 'Sonstiges' },
  { id: 'pale_moss_block', name: 'Bleichemoosblock', category: 'Sonstiges' },
  { id: 'pale_moss_carpet', name: 'Bleichemoosteppich', category: 'Sonstiges' },
  { id: 'pale_hanging_moss', name: 'Hängendes Bleichemoos', category: 'Sonstiges' },
  { id: 'eyeblossom', name: 'Augenblüte', category: 'Sonstiges' },
  { id: 'open_eyeblossom', name: 'Offene Augenblüte', category: 'Sonstiges' },
  { id: 'closed_eyeblossom', name: 'Geschlossene Augenblüte', category: 'Sonstiges' },
  { id: 'resin_block', name: 'Harzblock', category: 'Sonstiges' },
  { id: 'resin_bricks', name: 'Harzziegel', category: 'Sonstiges' },
  { id: 'chiseled_resin_bricks', name: 'Gemeißelte Harzziegel', category: 'Sonstiges' },
  { id: 'creaking_heart', name: 'Creaking-Herz', category: 'Sonstiges' },
];

export const BLOCK_CATEGORIES = [...new Set(MINECRAFT_BLOCKS.map(b => b.category))];

export const getBlocksByCategory = (category: string) => {
  return MINECRAFT_BLOCKS.filter(block => block.category === category);
};

export const getBlockById = (id: string) => {
  return MINECRAFT_BLOCKS.find(block => block.id === id);
};
